#!/usr/bin/env python3
"""Generate a TEST 4 card: flux-driven low-Mach convection in an adiabatic polytrope (snapy).

Phase 2 of the gravity-work study (STUDY_DESIGN.md, test 4). Derived from our earlier convection benchmark
deck (Anders & Brown 2017 polytrope, LMARS + WENO5, reflecting x1 walls, periodic x2), with the
forcing changed from a fixed superadiabatic excess to a FIXED ENERGY FLUX, so that the oracle
M_rms ~ eps^(1/3) (Edelmann et al. 2021) applies.

PRIMARIES (the only inputs; run_t4.py re-derives everything and aborts on disagreement)
    eps     dimensionless flux  F / (rho_t c_t^3), rho_t = 1, T_t = 1 at the top (z = Lz)
    n_rho   density scale heights of the initial polytrope
    gamma   ratio of specific heats (Rd = 1)
    aspect  Lx / Lz
    layer   heating / cooling layer thickness as a fraction of Lz (depth in cells = layer*nz)
    Re      nominal Reynolds number: nu = eps^(1/3) c_t Lz / Re (kinematic), the same Re at
            every eps, so M ~ eps^(1/3) is the exact low-Mach similarity law

DERIVED
    m    = 1/(gamma-1)               (adiabatic polytrope: neutral initial state)
    Lz   = exp(n_rho/m) - 1          T0 = 1 + Lz - z, rho0 = T0^m
    g    = (m+1) Rd T_t
    c_t  = sqrt(gamma Rd T_t)
    F    = eps rho_t c_t^3           -> forcing.bot-heat.flux = F, forcing.top-cool.flux = -F
    t_c  = Lz / (eps^(1/3) c_t)      nominal convective time; run lengths are quoted in t_c
    nu   = Lz^2 / (t_c Re)           forcing.diffusion.nu_iso; kappa_iso = 0

Explicit viscosity, no explicit conduction: the flux oracle is F_enth + F_KE + F_visc = F in
the interior; the remainder is numerical heat transport + unsteadiness. (Inviscid 2-D runs
were tried first: the inverse cascade piles KE into domain-scale rolls limited only by grid
dissipation, M_rms 0.57 at eps 1e-2 = ~30x the flux-limited speed. Conduction down the T
gradient is avoided because along an adiabat it carries 1.5 kappa rho, >> F at low eps.)
"""
import argparse
import math


def derive(eps, n_rho=2.0, gamma=5.0 / 3.0, aspect=2.0, layer=1.0 / 16.0, Re=300.0, Rd=1.0):
    m = 1.0 / (gamma - 1.0)
    Lz = math.exp(n_rho / m) - 1.0
    g = (m + 1.0) * Rd
    c_t = math.sqrt(gamma * Rd)
    F = eps * c_t ** 3
    t_c = Lz / (eps ** (1.0 / 3.0) * c_t)
    cp = gamma * Rd / (gamma - 1.0)
    nu = Lz * Lz / (t_c * Re)
    return dict(m=m, Lz=Lz, Lx=aspect * Lz, g=g, c_t=c_t, F=F, t_c=t_c, cp=cp, nu=nu,
                eps=eps, n_rho=n_rho, gamma=gamma, aspect=aspect, layer=layer, Re=Re, Rd=Rd)


def card(eps, nz, nx, scheme, gw, seed, tlim_tc, dt_out_tc, dt_rst_tc, n_rho=2.0,
         aspect=2.0, layer=1.0 / 16.0, Re=300.0, noise=1.0e-3, nlim=-1, cfl=0.4, nb2=1):
    d = derive(eps, n_rho=n_rho, aspect=aspect, layer=layer, Re=Re)
    depth = layer * nz
    if abs(depth - round(depth)) > 1e-9 or depth < 1:
        raise SystemExit(f"layer*nz = {depth} must be a positive integer")
    depth = int(round(depth))
    gw_lines = f"gravity-work: {gw}"
    tc = d["t_c"]
    return f"""# TEST 4 (gravity_work_physics): flux-driven low-Mach convection, snapy.
# GENERATED by T4_deck/make_card_t4.py --eps {eps:g} --nz {nz} --nx {nx} --scheme {scheme} --gw {gw} --seed {seed} --tlim-tc {tlim_tc:g} --Re {Re:g}
#   DERIVED (re-derived and verified by run_t4.py):
#     m = {d['m']!r}  Lz = {d['Lz']!r}  Lx = {d['Lx']!r}  g = {d['g']!r}
#     F = eps*rho_t*c_t^3 = {d['F']!r}  t_c = {tc!r}  (tlim = {tlim_tc:g} t_c)
#     heating/cooling layers: {depth} cells = {layer:g} Lz each; nu = {d['nu']!r} (Re = {Re:g})
geometry:
  type: cartesian
  bounds: {{x1min: 0., x1max: {d['Lz']!r}, x2min: 0., x2max: {d['Lx']!r}, x3min: 0., x3max: 1.}}
  cells: {{nx1: {nz}, nx2: {nx}, nx3: 1, nghost: 3}}

distribute: {{layout: slab, nb1: 1, nb2: {nb2}, nb3: 1, verbose: false}}

dynamics:
  equation-of-state:
    type: ideal-gas
    gammad: {d['gamma']!r}
    weight: 8.31446        # R_specific = Rd = 1 (A&B units)
    density-floor: 1.e-12
    pressure-floor: 1.e-12
    temperature-floor: 1.e-12   # the Kelvin default (20) would clamp this box
    limiter: true
  reconstruct:
    vertical:   {{type: weno5, scale: true, shock: false}}
    horizontal: {{type: weno5, scale: true, shock: false}}
  riemann-solver: {{type: lmars}}

boundary-condition:
  external:
    x1-inner: reflecting
    x1-outer: reflecting
    x2-inner: periodic
    x2-outer: periodic
    x3-inner: periodic
    x3-outer: periodic

integration:
  type: rk3
  cfl: {cfl}
  implicit-scheme: {scheme}
  nlim: {nlim}
  tlim: {tlim_tc * tc!r}
  ncycle_out: 1000

outputs:
  - {{type: netcdf, variables: [prim], dt: {dt_out_tc * tc!r}}}
  - {{type: restart, dt: {dt_rst_tc * tc!r}}}

forcing:
  const-gravity: {{grav1: {-d['g']!r}, {gw_lines}}}
  bot-heat: {{flux: {d['F']!r}, depth: {depth}}}
  top-cool: {{flux: {-d['F']!r}, depth: {depth}}}
  diffusion: {{nu_iso: {d['nu']!r}, kappa_iso: 0.}}

problem:
  eps: {eps!r}
  n_rho: {n_rho!r}
  gamma: {d['gamma']!r}
  aspect: {aspect!r}
  layer: {layer!r}
  Re: {Re!r}
  noise: {noise!r}
  seed: {seed}
"""


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--eps", type=float, required=True)
    p.add_argument("--nz", type=int, required=True)
    p.add_argument("--nx", type=int, required=True)
    p.add_argument("--scheme", type=int, default=0)
    p.add_argument("--gw", choices=["cell", "face"], required=True)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--tlim-tc", type=float, default=60.0)
    p.add_argument("--dt-out-tc", type=float, default=0.5)
    p.add_argument("--dt-rst-tc", type=float, default=5.0)
    p.add_argument("--nlim", type=int, default=-1)
    p.add_argument("--Re", type=float, default=300.0)
    p.add_argument("--nb2", type=int, default=1, help="x2 blocks = MPI-style ranks (srun -n nb2)")
    p.add_argument("-o", "--out", required=True)
    a = p.parse_args()
    with open(a.out, "w") as f:
        f.write(card(a.eps, a.nz, a.nx, a.scheme, a.gw, a.seed, a.tlim_tc, a.dt_out_tc,
                     a.dt_rst_tc, Re=a.Re, nlim=a.nlim, nb2=a.nb2))


if __name__ == "__main__":
    main()
