{
  "hash": "2db4fdb7bfdab5677a3e0368eda9525c",
  "result": {
    "engine": "jupyter",
    "markdown": "# Hydrostatic and well-balanced treatment {#sec-ch05}\n\n<!-- PROVENANCE\npin: snapy@e894700ff7aee30b52882e5202b16461413780b0 (chengcli/snapy)\nsources: OUTLINE.md chapter 5; docs/derivations/wb-ref4.md, wb-ref-wall.md, x1-centroid-spherical.md at the pin\nstatus: draft\n-->\n\nA stratified atmosphere at rest is the state snapy's $x_1$ sweep has to leave alone, and it is the hardest one:\nits pressure and density change by orders of magnitude along $x_1$, while the motions of interest are small\nperturbations of it. This chapter describes how the $x_1$ reconstruction keeps such a column at rest to round-off\nand how close the reference it uses comes to the column's own profile. It covers, in the order the code builds\nthem: the well-balanced $x_1$ reconstruction, which reconstructs perturbations about a discretely hydrostatic\nreference; the reference kernel, which builds that reference from a top-down pressure scan; its closure at a\nphysical wall; its continuity across $x_1$ block seams; the hydrostatic mode, which replaces gravity by the cell's\nown pressure difference; `balance_column`, which projects an initial column onto the scheme's discrete balance;\nthe fourth-order reference `SNAP_WB_REF4`; the $r^2$-exact $x_1$ maps `SNAP_X1_CENTROID_EXACT` of spherical-polar\ngrids; what is left of the $1/R$ term after them; and two legacy wall routines. The gravity work these schemes are\nused with is Chapter 6 (@sec-ch06); the switches and their tested combinations are Chapter 12.\n\nAll derivations of this chapter are checked by one executable check, `src/snapy_report/ch05/wbref_check.py`,\nwhose output `wbref_check.out` carries the claim tags `[C1]`–`[C21]`; claim `[C11]` is an independent rebuild of\nthe default reference from the equations of this chapter that reproduces the numbers snapy's own wall test prints.\n\n<!-- PENDING: the chapter's dependency map (STYLE.md section 10.1) is drawn from the switch coverage matrix of\n     Chapter 12 through the house dependency-map function, which is not in this tree yet. -->\n\n| scheme | switch | default | order | main test |\n|---|---|---|---|---|\n| WB $x_1$ reconstruction (@sec-ch05-wbx1) | gravity on | on | rest exact | `test_face_floor` |\n| Reference kernel (@sec-ch05-refkernel) | with the WB path | on | 2 ($\\rho_{\\mathrm{sf}}$) | `test_hydro_ref_x1` |\n| Wall clamp and continuation (@sec-ch05-wallclamp) | `wb-wall-clamp` | on | 2 at walls | `test_wb_ref_wall` |\n| Seam continuity (@sec-ch05-seam) | $x_1$ split | on | exact | `test_pref_local_seam` |\n| Hydrostatic mode (@sec-ch05-hsmode) | `non-hydrostatic` | 1 (off) | rest exact | `test_hydrostatic` |\n| `balance_column` (@sec-ch05-balcol) | API call | not called | fixed point | `test_balance_column` |\n| Fourth-order reference (@sec-ch05-wbref4) | `SNAP_WB_REF4` | off | 4 ($\\rho_{\\mathrm{sf}}$) | `test_wb_ref4_order` |\n| $r^2$-exact $x_1$ maps (@sec-ch05-x1cent) | `SNAP_X1_CENTROID_EXACT` | off | rest exact | `test_x1_centroid_rest` |\n| $1/R$ remainder (@sec-ch05-oneoverr) | none | — | $O(h^2/R)$ | none |\n| Legacy wall routines (@sec-ch05-legacy) | none | unreachable | — | none |\n\n: The schemes of this chapter. \"Order\" is the order of the face density reference $\\rho_{\\mathrm{sf}}$ against the\nexact profile where a number is given; \"rest exact\" means a discretely balanced column stays at rest to round-off.\nFull ctest names and tolerances are in each scheme's Tests layer and in the chapter's catalogue in Chapter 15. {#tbl-ch05-schemes}\n\n## Well-balanced $x_1$ reconstruction: perturbations about a hydrostatic reference (gravity on) {#sec-ch05-wbx1}\n\n<!-- PROVENANCE\npin: snapy@e894700ff7aee30b52882e5202b16461413780b0 (chengcli/snapy)\nsources: OUTLINE.md 5.1; src/hydro/hydro_forward.cpp; src/recon/reconstruct.cpp;\n         docs/derivations/wb-ref4.md@e894700ff7aee30b52882e5202b16461413780b0 §§1, 6\nstatus: draft\n-->\n\n### Summary\n\n::: {.callout-note title=\"At a glance\"}\n**What it does.** Reconstructs $p-p_{\\mathrm{ref}}$ and $\\rho-\\rho_{\\mathrm{ref}}$ along $x_1$ instead of $p$ and\n$\\rho$, then adds the reference face values back, so a discretely hydrostatic column produces no $x_1$ force.\n**Switch.** None. On whenever $g_1\\neq0$, the state has a pressure row and the EOS is not `shallow-water`; also\nunder an $x_1$ block split.\n**Requires.** The reference kernel (@sec-ch05-refkernel).\n**Order.** Exact rest balance; the face states keep the order of the reconstruction.\n**Defining equation.** @eq-ch05-wbx1-split.\n:::\n\nA column in hydrostatic balance has pressure and density that fall by orders of magnitude along $x_1$. A high-order\nreconstruction of $p$ itself returns face values whose difference across a cell is not exactly $\\rho g_1\\Delta x_1$,\nso a resting column feels a spurious vertical force of the size of the reconstruction error and starts to move.\nsnapy removes that force by construction: it builds, on every call, a reference $(p_{\\mathrm{ref}},\n\\rho_{\\mathrm{ref}})$ whose face pressures satisfy the discrete hydrostatic balance exactly, reconstructs only the\nperturbations about it, and restores the reference at the faces. The perturbation of a resting column is a constant,\nwhich every reconstruction reproduces, so the restored faces carry exactly the balanced pressure difference.\n\nThe scheme has no switch and no default to change: it is the $x_1$ path whenever gravity acts in $x_1$. The\nperturbation ghosts at a physical, non-outflow $x_1$ wall are filled with even parity; the reconstruction runs with\nits density and pressure floors off; and a face value that comes out non-positive falls back to the reference\npressure or to the density of the adjacent cell. The $x_2$ and $x_3$ sweeps have no such treatment.\n\n*Aliases.* \"WB\" or \"well-balanced reconstruction\" in comments and commit messages; the \"base\" reference of\n`docs/derivations/wb-ref4.md@e894700ff7aee30b52882e5202b16461413780b0` §1.\n\n### Derivation\n\nUnits: $p$ [Pa], $\\rho$ [kg m$^{-3}$], $g_1$ [m s$^{-2}$], $x_1$ and $\\Delta x_1$ [m]. This layer uses cell averages\nand face point values; a cell average carries an overbar only where a point value of the same quantity appears.\n\nThe $x_1$ momentum equation with constant gravity is $\\partial_t(\\rho v_1)+\\partial_1(\\rho v_1^2+p)=\\rho g_1$.\nIntegrated over cell $i$ of a Cartesian column, with $p^{*}_{i\\pm1/2}$ the face pressures of the Riemann solver,\n\n$$\n\\frac{\\mathrm{d}}{\\mathrm{d}t}(\\overline{\\rho v_1})_i = -\\frac{\\Delta_i[\\rho v_1^2+p^{*}]}{\\Delta x_1} + \\overline{\\rho}_i g_1 .\n$$\n\nAt rest the advective part vanishes and the cell stays at rest exactly when\n$p^{*}_{i+1/2}-p^{*}_{i-1/2}=g_1\\overline{\\rho}_i\\Delta x_1$. The reference kernel (@sec-ch05-refkernel) builds face\npressures $p_{\\mathrm{sf}}$ that satisfy this difference identically, @eq-ch05-refkernel-scan, together with a cell\npressure $p_{\\mathrm{ref},i}$, a cell density $\\rho_{\\mathrm{ref},i}$ and a face density $\\rho_{\\mathrm{sf}}$. The\nreconstruction then works on the perturbations and restores the reference at the faces:\n\n$$\n\\begin{aligned}\np'_i &= \\overline{p}_i - p_{\\mathrm{ref},i}, \\\\\n\\rho'_i &= \\overline{\\rho}_i - \\rho_{\\mathrm{ref},i}, \\\\\np^{L,R}_{i-1/2} &= \\mathcal R^{L,R}[p']_{i-1/2} + p_{\\mathrm{sf},i-1/2}, \\\\\n\\rho^{L,R}_{i-1/2} &= \\mathcal R^{L,R}[\\rho']_{i-1/2} + \\rho_{\\mathrm{sf},i-1/2},\n\\end{aligned}\n$$ {#eq-ch05-wbx1-split}\n\nwith $\\mathcal R^{L,R}$ the left and right face values of the configured $x_1$ reconstruction. The subtraction in\n@eq-ch05-wbx1-split is done by `_hydro_ref_x1` and the two in-place updates that follow it\n([`hydro_forward.cpp:288-293`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L288-L293)),\nand the restore by `psf_lo` added back to both states\n([`hydro_forward.cpp:357-363`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L357-L363)).\n\nSuppose now that $p'_i=c$ in every cell, for one constant $c$, and $v_1=0$. Every reconstruction of snapy returns a\nconstant exactly, so $p^{L}=p^{R}=p_{\\mathrm{sf}}+c$ at every face, the two states agree, and the Riemann solver\nreturns $p^{*}=p_{\\mathrm{sf}}+c$ with zero mass and energy flux. The momentum balance above then reads\n$-(p_{\\mathrm{sf},i+1/2}-p_{\\mathrm{sf},i-1/2})/\\Delta x_1+\\overline{\\rho}_ig_1=0$ by @eq-ch05-refkernel-scan. The\ndiscrete rest state of the scheme is therefore\n\n$$\n\\overline{p}_i = p_{\\mathrm{ref},i}(\\overline{p},\\overline{\\rho}) + c \\quad\\text{in every cell},\n$$ {#eq-ch05-wbx1-rest}\n\nwhatever the density reference is: with $v_1=0$ the face density enters no flux. Because $p_{\\mathrm{ref}}$ is rebuilt\nfrom the state, @eq-ch05-wbx1-rest is a fixed-point condition on the column, which `balance_column` solves\n(@sec-ch05-balcol). On spherical-polar grids the face areas and the geometric pressure source enter the same\ncancellation; the plain-mean form is @sec-ch05-x1cent. The derivation follows\n`docs/derivations/wb-ref4.md@e894700ff7aee30b52882e5202b16461413780b0` §§1, 6.\n\n*Exact and truncated.* The rest balance is exact for any column satisfying @eq-ch05-wbx1-rest. Away from rest the\nface states carry the reconstruction's truncation error on the perturbation plus the offset\n$\\rho_{\\mathrm{sf}}-\\mathcal R[\\rho_{\\mathrm{ref}}]$ of the density reference, which is $O(\\Delta x_1^2)$ for the\ndefault reference (`[C14]`) and $O(\\Delta x_1^4)$ with @sec-ch05-wbref4. The identity used in the cancellation,\nthat the hydrostatic correction and the pressure force cancel at rest, is `[C19]`.\n\n### Numerical method\n\nWhere things live: $\\overline p$, $\\overline\\rho$ and the perturbations are cell averages; $p_{\\mathrm{sf}}$ and\n$\\rho_{\\mathrm{sf}}$ are face point values at the lower face of each cell; the reconstructed states are face\nvalues. The scheme runs in every RK stage, in the $x_1$ block of `HydroImpl::forward`, explicitly.\n\n**Ghosts.** At a physical $x_1$ wall whose boundary function is not an outflow, the $n_g$ ghost cells of $p'$ and\n$\\rho'$ are overwritten with the mirror image of the first $n_g$ interior cells, even parity, while the velocity keeps\nthe odd ghosts of the reflecting boundary (@fig-ch05-wbx1-ghosts). A resting perturbation ($p'=c$) is then constant\nacross the wall too. At an $x_1$ seam the ghosts are the neighbour's cells and the reference is made continuous by\n@sec-ch05-seam; at an outflow boundary the ghosts are left as the boundary function wrote them.\n\n::: {#cell-fig-ch05-wbx1-ghosts .cell execution_count=1}\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Perturbation ghosts at a reflecting x1 wall (thick black line), x1 increasing to the right. Top row: the perturbations p' and rho' (sky-blue circles) in three interior cells are mirrored with even parity into the three hatched reddish-purple ghost cells. Bottom row: the normal velocity (black arrows) is mirrored with odd parity. A constant perturbation stays constant across the wall, so a resting column sees no wall force.](05-well-balanced_files/figure-html/fig-ch05-wbx1-ghosts-output-1.svg){#fig-ch05-wbx1-ghosts fig-alt='Two rows of cells with a thick wall line between three hatched ghost cells on the left and three interior cells on the right; circles mirrored at equal heights in the top row, arrows mirrored with reversed direction in the bottom row.'}\n:::\n:::\n\n\n**Floors.** The reconstruction of the perturbations is called with `floor=false`, because a perturbation is\nlegitimately negative and the density and pressure floors would clamp it; the passive-species rows are still\nclamped at zero when the EOS limiter is on. After the restore, a non-positive face pressure is replaced by\n$p_{\\mathrm{sf}}$; a non-positive left density at face $i-\\tfrac12$ by $\\overline\\rho_{i-1}$ and a non-positive\nright density by $\\overline\\rho_i$, the cell on the same side. The adjacent cell, and not $\\rho_{\\mathrm{sf}}$, is\nused because a reference that overestimates the density aloft turns every floor event at a reflecting top wall into\na large spurious impedance. The shift that builds $\\overline\\rho_{i-1}$ replicates the first cell instead of\nwrapping around the column. @sec-ch08 owns the positivity floors in general.\n\n**Order.** In the interior the face states have the order of the reconstruction applied to a smooth perturbation,\nplus the density-reference offset above; at rest the result is exact in interior, wall and seam cells alike. A\ncolumn that is not at the fixed point @eq-ch05-wbx1-rest has a residual force of the size of\n$p'_i-c$, which is what `balance_column` removes.\n\n### Code\n\n| what | code link | symbol | switch |\n|--------|----------|----------|------|\n| the gate | [`hydro_forward.cpp:262-263`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L262-L263) | `wb_x1` | $g_1\\neq0$, not shallow water |\n| reference and subtraction | [`hydro_forward.cpp:288-293`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L288-L293) | `_hydro_ref_x1` | |\n| even-parity ghosts | [`hydro_forward.cpp:300-312`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L300-L312) | `is_outflow` | physical, non-outflow walls |\n| reconstruction without floors | [`hydro_forward.cpp:346-348`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L346-L348) | `precon1` | |\n| pressure restore and fallback | [`hydro_forward.cpp:357-360`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L357-L360) | `psf_lo` | |\n| density restore and fallback | [`hydro_forward.cpp:362-377`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L362-L377) | `rho_below` | |\n| species clamp that stays | [`reconstruct.cpp:150-155`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/recon/reconstruct.cpp#L150-L155) | `clamp_min_` | EOS limiter |\n| the non-WB $x_1$ path | [`hydro_forward.cpp:378-384`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L378-L384) | `_revise_x1inner_lr` | shallow water, $g_1=0$ |\n\n: Code map of the well-balanced $x_1$ reconstruction. {#tbl-ch05-wbx1-code}\n\nIn the $x_1$ block of `HydroImpl::forward`, in step order (code indices `is`, `iu` are the first and last interior\ncell, $i_s$ and $i_u$):\n\n1. `wb_x1` is set from the gravity, the number of state rows and the EOS type\n   ([`hydro_forward.cpp:262-263`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L262-L263)).\n2. Under `SNAP_X1_CENTROID_EXACT` on spherical-polar grids the input `wx1` becomes the plain-mean view of\n   @sec-ch05-x1cent; otherwise `wx1` is the state itself.\n3. `_hydro_ref_x1` returns $p_{\\mathrm{sf}}$, $p_{\\mathrm{ref}}$, $\\rho_{\\mathrm{sf}}$ and $\\rho_{\\mathrm{ref}}$, and the\n   two rows of `wx1` are replaced by the perturbations\n   ([`hydro_forward.cpp:288-293`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L288-L293)).\n4. The even-parity ghosts are written where `is_outflow` is false at a physical wall\n   ([`hydro_forward.cpp:300-312`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L300-L312)).\n5. Under `SNAP_X1_MASS_COVARIANCE` the velocity row is corrected before the reconstruction (Chapter 4).\n6. `precon1` reconstructs with `floor=false`\n   ([`hydro_forward.cpp:346-348`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L346-L348)).\n7. The rows of `wx1` are restored, `psf_lo` is added to both pressure states with its fallback\n   ([`hydro_forward.cpp:357-360`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L357-L360)),\n   and the density states get `dsf` with the `rho_below` and own-cell fallbacks\n   ([`hydro_forward.cpp:362-377`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L362-L377)).\n\nNo switch is read here and no warning is issued; the setup checks of the reference are in @sec-ch05-refkernel and\n@sec-ch05-wbref4.\n\n### Tests\n\n| test (ctest name) | what it asserts | tolerance | where the tolerance comes from |\n|----------------|-------------|-----|-----|\n| `tests/test_face_floor.cpp` (`test_face_floor.release`), `face_floor_uses_adjacent_density` | dipped column: lower-face mass flux 4.07888; at the dipped face $\\lvert$mass flux$\\rvert<10^{-9}$ and momentum flux $>0.03042$ | $10^{-3}$ abs; $10^{-9}$; bound | the adjacent-density floor gives $-6.3\\times10^{-11}$, a $\\rho_{\\mathrm{sf}}$ floor $-9.5\\times10^{-8}$ (test header) |\n| same, `face_floor_fires_on_an_unresolved_column` | an unresolved column floors to the adjacent density in every arm: flux $2.83191\\times10^{-8}$ | $10^{-5}$ relative | pinned value of the wall closure |\n| `tests/test_wb_wall_corner.cpp` (`test_wb_wall_corner.release`) | a uniform-in-$x_2$ balanced polytrope keeps $\\lvert u_2\\rvert/c_s$ and $\\lvert v\\rvert/c_s\\le10^{-12}$; an $x_2$ split equals one block | $10^{-12}$; exact | round-off of a balanced column |\n| `tests/test_hydrostatic.cpp` (`test_hydrostatic.release`) | a cubed-sphere hydrostatic atmosphere stays at rest for 100 steps | $10^{-8}$ | round-off margin |\n| this chapter's check, `[C14]`, `[C19]` | density-reference offset; cancellation at rest | per claim | stated in the check |\n\n: Tests of the well-balanced $x_1$ reconstruction. {#tbl-ch05-wbx1-tests}\n\n**Evidence.** All entries above pass at the pin [sha `e894700ff7aee30b52882e5202b16461413780b0`; decks: the test\nfiles named; run: `ctest -V` of the chapter's 28 entries on a Release build of the pin, 2026-10-10, CPU, double,\n1 rank except the `_mp` entries (2 ranks)]. Printed values from that run: `test_hydrostatic` maximum spurious\nvertical velocity after 100 steps $7.84\\times10^{-15}$; `test_face_floor` unresolved-column dipped-face mass flux\n$2.8319\\times10^{-8}$ in the default, `_wb_ref4` and `_x1_centroid` arms; `test_wb_wall_corner` CPU corner errors 0.\n**Coverage.** CPU only in that run (the build had CUDA off, so every `_cuda` case was skipped); the CUDA arms\n`face_floor_*_cuda` and `*_cuda` of `test_wb_wall_corner` exist and compare CUDA with CPU to $10^{-5}$ relative\nand exactly: **pending: a CUDA run at the pin**. Multi-rank: through the seam tests of @sec-ch05-seam only.\n\n### Limits\n\n::: {.callout-warning title=\"Limits\"}\nThe $x_2$ and $x_3$ reconstructions have no well-balanced treatment. A column that is hydrostatic in the continuum\nbut not at the discrete fixed point @eq-ch05-wbx1-rest is not at rest.\n:::\n\n1. **No horizontal treatment.** The $x_2$ and $x_3$ sweeps reconstruct the full state\n   (`precon23` [`hydro_forward.cpp:549-551`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L549-L551));\n   on a curved grid a stratified column is therefore balanced in $x_1$ only.\n2. **Floors off for the perturbation, but not for species.** The species clamp at zero still applies under the EOS\n   limiter (table above). Not measured as a source of imbalance.\n3. **Moist columns.** No reference meets the floor of a moist column in every case; the choice of reference is a\n   parked study (chengcli/snapy#275) and there is no YAML key to choose it (chengcli/snapy#281).\n4. **Untested combinations.** See the switch coverage matrix of Chapter 12.\n\n\n## Hydrostatic reference kernel: face-pressure scan, cell pressure and density reference (with the WB path) {#sec-ch05-refkernel}\n\n<!-- PROVENANCE\npin: snapy@e894700ff7aee30b52882e5202b16461413780b0 (chengcli/snapy)\nsources: OUTLINE.md 5.2; src/hydro/hydro_ref_x1_impl.h; src/hydro/hydro.cpp; src/hydro/hydro_dispatch.cpp;\n         src/hydro/hydro_dispatch.cu; docs/derivations/wb-ref4.md@e894700ff7aee30b52882e5202b16461413780b0 §§1, 2, 6;\n         sources/canoe__tall_column_instability_TECH_REPORT.md §§3d, 4-5\nstatus: draft\n-->\n\n### Summary\n\n::: {.callout-note title=\"At a glance\"}\n**What it does.** Builds, per column and per call, the face pressures $p_{\\mathrm{sf}}$ by a top-down hydrostatic\nscan, the cell pressure $p_{\\mathrm{ref}}$ from them, and the density references $\\rho_{\\mathrm{ref}}$ and\n$\\rho_{\\mathrm{sf}}$ from a smoothed $\\rho/p$.\n**Switch.** None: always with the well-balanced path (@sec-ch05-wbx1).\n**Order.** $p_{\\mathrm{sf}}$ exact up to one column constant; $p_{\\mathrm{ref}}$ $O(\\Delta x_1^6)$ on uniform grids;\n$\\rho_{\\mathrm{sf}}$ $O(\\Delta x_1^2)$.\n**Defining equation.** @eq-ch05-refkernel-scan.\n:::\n\nThe kernel is the reference of @eq-ch05-wbx1-split. Its face pressures are the discrete hydrostatic balance itself,\nsummed from an anchor at the top of the column, so the rest balance of the well-balanced reconstruction holds\nidentically. Its cell pressure is the cell average of a quintic through six face pressures, which matches the\ncell average of a smooth hydrostatic pressure to sixth order up to the same column constant; on a non-uniform grid it\nis a log-mean instead, exact only for an isothermal cell. Its density reference is the cell pressure times a\nsmoothed $\\rho/p$: smoothed, because an unsmoothed ratio makes the density perturbation a copy of the pressure\nperturbation and the entropy mode would bypass the reconstruction.\n\nThe kernel has a C++ implementation shared by the CPU and CUDA paths and a tensor implementation for MPS. The wall\nclosure of the smoothed ratio and of the six-face rows is @sec-ch05-wallclamp; the anchor relay across $x_1$ seams is\n@sec-ch05-seam; the fourth-order replacement of the density reference is @sec-ch05-wbref4.\n\n*Aliases.* \"smooth5\" (the five-point binomial) and \"the base reference\" in\n`docs/derivations/wb-ref4.md@e894700ff7aee30b52882e5202b16461413780b0` §1.\n\n### Derivation\n\nUnits as in @sec-ch05-wbx1; $g=-g_1>0$ [m s$^{-2}$] is the downward magnitude the kernel takes; $r=\\rho/p$\n[s$^2$ m$^{-2}$]. Cell $i$ spans $[x_{1,i-1/2},x_{1,i+1/2}]$, and $\\Delta x_{1,i}$ is its width.\n\n#### Face pressures\n\nHydrostatic balance integrated over cell $i$ gives\n$p(x_{1,i-1/2})-p(x_{1,i+1/2})=g\\int_{\\mathrm{cell}}\\rho\\,\\mathrm{d}x_1=g\\,\\overline\\rho_i\\Delta x_{1,i}$ exactly, for\nthe cell average $\\overline\\rho_i$. The kernel defines the face pressures by this relation,\n\n$$\np_{\\mathrm{sf},i-1/2} = p_{\\mathrm{sf},i+1/2} + g\\,\\overline{\\rho}_i\\,\\Delta x_{1,i},\n$$ {#eq-ch05-refkernel-scan}\n\ndownward from the top face of the top interior cell $i_u$ and upward into the upper ghosts, clipped below at the\nsmallest positive normal number. @eq-ch05-refkernel-scan is `hydro_ref_x1_scan_impl`\n([`hydro_ref_x1_impl.h:22-60`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L22-L60)).\nSince each step is exact, $p_{\\mathrm{sf}}$ equals the exact face pressure of a hydrostatic column plus one constant\nper column, set by the anchor (`[C13]`: spread of $p_{\\mathrm{sf}}-p(x_{1,f})$ $2.2\\times10^{-16}$ of $p$). On a\nsingle block the anchor extrapolates the top cell isothermally by half a cell,\n\n$$\np_{\\mathrm{sf},i_u+1/2} = \\overline{p}_{i_u}\\exp\\!\\left(-\\frac{g\\,\\Delta x_{1,i_u}}{2\\,\\overline{p}_{i_u}/\\overline{\\rho}_{i_u}}\\right),\n$$ {#eq-ch05-refkernel-anchor}\n\nthe branch that sets `top_anchor`\n([`hydro_ref_x1_impl.h:30-38`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L30-L38)).\nIt uses the cell averages, so even on an isothermal column it is off by the factor\n$\\sinh a/a=1+a^2/6+O(a^4)$, $a=\\Delta x_1/2H$ with $H=p/(\\rho g)$ (`[C10]`). That offset is a column constant and drops\nout of the rest balance (@eq-ch05-wbx1-rest holds for any $c$).\n\n#### Cell pressure\n\nOn a uniform grid the cell pressure is the cell average of the quintic through the six faces\n$i-\\tfrac52,\\dots,i+\\tfrac52$:\n\n$$\n\\begin{aligned}\np_{\\mathrm{ref},i} = \\tfrac{1}{1440}\\big(&11\\,p_{\\mathrm{sf},i-5/2} - 93\\,p_{\\mathrm{sf},i-3/2} + 802\\,p_{\\mathrm{sf},i-1/2} \\\\\n&\\qquad + 802\\,p_{\\mathrm{sf},i+1/2} - 93\\,p_{\\mathrm{sf},i+3/2} + 11\\,p_{\\mathrm{sf},i+5/2}\\big),\n\\end{aligned}\n$$ {#eq-ch05-refkernel-pref}\n\nweights derived exactly in `[C1]` and coded as `w6`\n([`hydro_ref_x1_impl.h:140-156`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L140-L156)).\nIn the two cells next to an array end or a clamped wall the same average is taken over six one-sided faces, rows\n`w6e` (`[C2]`, @sec-ch05-wallclamp). A value outside $[\\min,\\max]$ of the cell's own two face pressures is rejected\nand the face mean is kept. Because the faces are exact up to $c$, $p_{\\mathrm{ref},i}=\\overline p_i+c+O(\\Delta\nx_1^6)$ (`[C13]`: fitted order 5.87 on an isothermal column, $n_1$ = 8, 16, 32).\n\nOn a non-uniform grid, where the relative spread of the face widths is $10^{-10}$ of their mean or more (`[C20]`),\nthe cell pressure is the log-mean\n\n$$\np_{\\mathrm{ref},i} = \\frac{g\\,\\overline{\\rho}_i\\,\\Delta x_{1,i}}{\\ln(p_{\\mathrm{sf},i-1/2}/p_{\\mathrm{sf},i+1/2})},\n$$ {#eq-ch05-refkernel-logmean}\n\nor the face mean when `ratio` is within $10^{-6}$ of one\n([`hydro_ref_x1_impl.h:181-186`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L181-L186)).\nFor an isothermal cell $p$ is exponential in $x_1$, and its cell average is exactly @eq-ch05-refkernel-logmean; for a\npolytrope it is $O(\\Delta x_1^2)$ (`[C9]`: relative error $1.5\\times10^{-4}$ at $\\Delta x_1=0.05$, order 2.02).\n\n#### Density references\n\nWith $r_i=\\overline\\rho_i/\\overline p_i$, the smoothed ratio is the binomial $r^{s}_i=\\tfrac1{16}(r_{i-2}+4r_{i-1}+6r_i+4r_{i+1}+r_{i+2})$,\nand the references are\n\n$$\n\\begin{aligned}\n\\rho_{\\mathrm{ref},i} &= p_{\\mathrm{ref},i}\\,r^{s}_i, \\\\\n\\rho_{\\mathrm{sf},i-1/2} &= p_{\\mathrm{sf},i-1/2}\\,\\tfrac12\\big(r^{s}_{i-1}+r^{s}_i\\big),\n\\end{aligned}\n$$ {#eq-ch05-refkernel-dens}\n\ncoded as `dref` and `dsf`\n([`hydro_ref_x1_impl.h:193-200`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L193-L200)),\nwith the binomial in `hydro_ref_x1_rop_smooth`\n([`hydro_ref_x1_impl.h:86-108`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L86-L108)).\nAt array index 0 the face density uses $r^s_0$ alone.\n\n*Why smoothed.* Take the unsmoothed ratio instead, $\\rho_{\\mathrm{ref},i}=p_{\\mathrm{ref},i}\\overline\\rho_i/\\overline p_i$.\nThen $\\rho'_i=\\overline\\rho_i-p_{\\mathrm{ref},i}\\overline\\rho_i/\\overline p_i=\\overline\\rho_i\\,p'_i/\\overline p_i$, so\n$\\rho'/\\overline\\rho=p'/\\overline p$ in every cell: the density perturbation carries no information the pressure\nperturbation does not, and an entropy (buoyancy) anomaly is not reconstructed as a density perturbation at all. The\nbinomial keeps the reference on the large scales of the column only. It has unit sum, zero first moment and second\nmoment 1 in cells, and zero response at the grid scale (`[C3]`), so $r^{s}_i=r_i+\\tfrac{\\Delta x_1^2}{2}r''+O(\\Delta\nx_1^4)$. This re-derives the degeneracy stated in the comment above `hydro_ref_x1_rop_smooth`; the measurements behind\nit are in `sources/canoe__tall_column_instability_TECH_REPORT.md` §§3d, 4-5.\n\n*Face-density offset.* What the solver uses is $\\rho_{\\mathrm{sf}}+\\mathcal R[\\overline\\rho-\\rho_{\\mathrm{ref}}]\n=\\mathcal R[\\overline\\rho]+\\delta\\rho_f$ with $\\delta\\rho_f=\\rho_{\\mathrm{sf}}-\\mathcal R[\\rho_{\\mathrm{ref}}]$. Expanding\nthe ratio of averages, the binomial bias, the two-cell mean and the cell pressure,\n`docs/derivations/wb-ref4.md@e894700ff7aee30b52882e5202b16461413780b0` §2 obtains\n\n$$\n\\delta\\rho_f = \\frac{\\Delta x_1^2}{12}\\big(p'R'+2pR''\\big) + O(\\Delta x_1^4),\n$$ {#eq-ch05-refkernel-offset}\n\nwith $R=\\rho/p$ the point ratio and primes $x_1$ derivatives (this paragraph only). `[C14]` measures $\\delta\\rho_f$ at\nthe middle face of a polytrope against fifth-order linear reconstruction and finds the ratio to\n@eq-ch05-refkernel-offset 1.0022, 1.0005, 1.0001, 1.0000 at $n_1$ = 32 to 256, order 2.00.\n\n*Exact and truncated.* Exact: the scan step, hence the rest balance. $O(\\Delta x_1^6)$: the uniform cell pressure.\n$O(\\Delta x_1^2)$: the log-mean on non-isothermal cells, the smoothed ratio and the face density reference.\n\n### Numerical method\n\n@fig-ch05-refkernel-scan shows the stencils. The scan is serial along each column; the per-cell part reads six face\npressures and five ratios. The kernel runs once per $x_1$ sweep, in every RK stage, on cell averages (on plain means\nunder @sec-ch05-x1cent), including ghost cells: ghosts get face pressures from the upward scan and, without the wall\nclamp, ghost ratios enter the binomial. Uniformity is decided once per block from its own `dx1f`.\n\n::: {#cell-fig-ch05-refkernel-scan .cell execution_count=2}\n\n::: {.cell-output .cell-output-display execution_count=2}\n![The reference kernel on one column between two walls (thick black lines), x1 to the right. Top: the scan (bluish-green arrow) starts from the top anchor and adds g rho_i dx1 cell by cell; face pressures are orange triangles. Bottom: the six faces whose quintic gives the interior cell pressure of cell i, and the one-sided six-face window used for the two cells next to a wall. Shaded cells are the cells whose pressure the windows define.](05-well-balanced_files/figure-html/fig-ch05-refkernel-scan-output-1.svg){#fig-ch05-refkernel-scan fig-alt='Two rows of eight cells between thick wall lines; an arrow over the top row runs from right to left, triangles mark faces; brackets in the bottom row span six faces around cell i and six faces starting at the wall.'}\n:::\n:::\n\n\n**Paths.** CPU and CUDA run the same header functions: one CPU loop over columns, one CUDA block per column whose\nthread 0 scans and whose threads then fill the cells. The MPS path rebuilds the same quantities with tensor\noperations (cumulative sums, a padded binomial), and `test_hydro_ref_x1` compares it with the CPU path.\n\n**Order.** As in the Derivation layer, interior; at walls see @sec-ch05-wallclamp; at seams the reference is the\nneighbour's (@sec-ch05-seam).\n\n### Code\n\n| what | code link | symbol | switch |\n|--------|----------|----------|------|\n| the call and the uniform test | [`hydro.cpp:535-556`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L535-L556) | `x1_uniform_` | spread $<10^{-10}$ |\n| scan and anchor | [`hydro_ref_x1_impl.h:22-60`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L22-L60) | `hydro_ref_x1_scan_impl` | |\n| binomial ratio | [`hydro_ref_x1_impl.h:86-108`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L86-L108) | `hydro_ref_x1_rop_smooth` | |\n| cell pressure, both grids | [`hydro_ref_x1_impl.h:136-186`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L136-L186) | `use_six_faces` | uniform |\n| thin-block and fit guards | [`hydro_ref_x1_impl.h:124-135`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L124-L135) | `fits` | |\n| density references | [`hydro_ref_x1_impl.h:188-200`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L188-L200) | `dsf` | |\n| CPU path | [`hydro_dispatch.cpp:14-35`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_dispatch.cpp#L14-L35) | `hydro_ref_x1_cpu` | |\n| MPS tensor path | [`hydro_dispatch.cpp:37-200`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_dispatch.cpp#L37-L200) | `hydro_ref_x1_mps` | |\n| CUDA kernel | [`hydro_dispatch.cu:12-31`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_dispatch.cu#L12-L31) | `hydro_ref_x1_cuda_kernel` | CUDA build |\n\n: Code map of the reference kernel. {#tbl-ch05-refkernel-code}\n\n1. `HydroImpl::_hydro_ref_x1` classifies the block once as uniform or not and caches it in `x1_uniform_`\n   ([`hydro.cpp:535-541`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L535-L541)).\n2. It reads whether each $x_1$ end is a physical boundary and calls the dispatch stub `call_hydro_ref_x1` with the\n   wall-clamp option\n   ([`hydro.cpp:550-556`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L550-L556)).\n3. Per column, `hydro_ref_x1_impl` runs the scan and then the cell function for every cell\n   ([`hydro_ref_x1_impl.h:203-215`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L203-L215)).\n4. In the cell function, the guards `thin` and `fits` decide whether one-sided rows may be used\n   ([`hydro_ref_x1_impl.h:124-135`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L124-L135)),\n   then the cell pressure is formed by `use_six_faces` or the log-mean\n   ([`hydro_ref_x1_impl.h:136-186`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L136-L186)),\n   and the two density references by @eq-ch05-refkernel-dens.\n5. The fourth-order replacement (@sec-ch05-wbref4) and the seam exchange (@sec-ch05-seam) follow in `_hydro_ref_x1`.\n\nNo switch is read and no warning is issued by the kernel. A block with fewer interior $x_1$ cells than ghosts makes\nthe one-sided rows unusable (`fits` false), and the face mean is kept.\n\n### Tests\n\n| test (ctest name) | what it asserts | tolerance | where the tolerance comes from |\n|----------------|-------------|-----|-----|\n| `tests/test_hydro_ref_x1.cpp` (`test_hydro_ref_x1.release`), `cpu_matches_tensor_reference` | the CPU path equals the MPS tensor implementation run on CPU | $2\\times10^{-12}$ double, $2\\times10^{-5}$ float | round-off of two summation orders |\n| same, `wall_clamp_keeps_the_interior_free_of_the_ghosts` and its control | with the clamp, changing ghosts leaves interior references unchanged; without, they change | exact (`torch::equal`) | the property is structural |\n| same, `a_thin_block_keeps_the_interior_free_of_the_ghosts` and control | as above on a block of fewer than five cells | exact | structural |\n| same, `the_wall_reference_does_not_depend_on_the_blocks_x1_size` | the wall-cell reference is the same on blocks of different $x_1$ size | $10^{-14}$ relative | round-off |\n| same, `cuda_matches_cpu` | CUDA equals CPU | per dtype | round-off |\n| `tests/test_hydro_options.cpp` (`test_hydro_options.release`), `wb_wall_clamp_ships_enabled`, `wb_wall_clamp_reaches_the_x1_reference` | the clamp defaults on and changes the reference | differ by more than $10^{-13}$ | non-vacuity |\n| this chapter's check | `[C1]`–`[C3]`, `[C9]`, `[C10]`, `[C13]`, `[C14]`, `[C20]` | per claim | stated in the check |\n\n: Tests of the reference kernel. {#tbl-ch05-refkernel-tests}\n\n**Evidence.** `test_hydro_ref_x1.release` (6 passed, `cuda_matches_cpu` skipped) and `test_hydro_options.release`\n(11 passed, the `_cuda` case skipped) pass at the pin [sha `e894700ff7aee30b52882e5202b16461413780b0`; decks: the\ntest files; run: `ctest -V`, Release build, 2026-10-10, CPU, double, 1 rank]. Check numbers: [sha: the formulas of\nsnapy@e894700ff7aee30b52882e5202b16461413780b0, rebuilt from this section's equations; deck: the check itself; run:\n`python3 wbref_check.py`, numpy 2.2.4, sympy 1.14.0, double].\n**Coverage.** CPU in the run above; CUDA cases exist but were not run (**pending: a CUDA run at the pin**); the MPS\npath itself is compared only through its CPU execution; multi-rank through @sec-ch05-seam.\n\n### Limits\n\n::: {.callout-warning title=\"Limits\"}\nOn a stretched $x_1$ grid the cell pressure is the log-mean, exact only for isothermal cells, so a column at rest is\nat rest to round-off only after `balance_column`.\n:::\n\n1. **Non-uniform grids.** The log-mean is a different operator from the six-face rows, not a lower-order version of\n   them, and the reconstruction weights are uniform-spacing on every grid. A stretched-grid rest residual of\n   $7.37\\times10^{-4}$, the same for every density form, is reported in chengcli/snapy#250\n   (`sources/gh__ISSUE_THREADS_138-250.md`; measured before the pin, not re-run here); chengcli/snapy#280 tracks it.\n   chengcli/snapy#280 also states that the face interpolation uses fixed rationals on stretched grids; at the pin the\n   rationals are used only on a uniform block and the log-mean otherwise.\n2. **No positivity guard on $\\rho/p$.** The ratio divides by the cell pressure without a guard (chengcli/snapy#250\n   §2). Not measured at the pin.\n3. **One classification per block.** A grid uniform over part of the column gives different operators to different\n   blocks; `balance_column` must make the same choice (@sec-ch05-balcol).\n4. **Untested combinations.** See the switch coverage matrix of Chapter 12.\n\n\n## Wall clamp and the wall continuation of the default reference (`dynamics/wb-wall-clamp`) {#sec-ch05-wallclamp}\n\n<!-- PROVENANCE\npin: snapy@e894700ff7aee30b52882e5202b16461413780b0 (chengcli/snapy)\nsources: OUTLINE.md 5.3; src/hydro/hydro_ref_x1_impl.h; src/hydro/hydro_dispatch.cpp; src/hydro/hydro_options.cpp;\n         docs/derivations/wb-ref-wall.md@e894700ff7aee30b52882e5202b16461413780b0 §§1-5; the wall-closure patches in\n         sources/team-notes/\nstatus: draft\n-->\n\n### Summary\n\n::: {.callout-note title=\"At a glance\"}\n**What it does.** Keeps every reference stencil inside the owned cells at a physical $x_1$ wall: one-sided six-face\nrows for the two wall cells, and $\\rho/p$ continued past the wall from the two owned cells next to it.\n**Switch.** YAML `dynamics/wb-wall-clamp`, default `true`.\n**Order.** $\\rho_{\\mathrm{sf}}$ second order at faces 0-2 next to each wall (first order with the wall cell repeated).\n**Defining equation.** @eq-ch05-wallclamp-cont.\n:::\n\nThe ghost cells of a reflecting wall hold the mirror image of the interior, which is the right input for the\nRiemann solver but not a hydrostatic continuation of the column: a stratified profile mirrored at the wall has a kink.\nAny reference stencil that reads a ghost therefore puts that kink into $p_{\\mathrm{ref}}$ and $\\rho_{\\mathrm{ref}}$\nnext to the wall. With the clamp on, the cell pressure of the two cells next to a physical wall uses one-sided\nsix-face rows, and the binomial of $\\rho/p$ no longer reads ghosts. What it reads instead is the wall continuation:\nthe ratio continued linearly from the two owned cells where it rises towards the wall, and ln-linearly where it\nfalls. A plain repetition of the wall cell, the first version of the clamp, is exact only for constant $\\rho/p$ and\nleaves the face density reference first order at the three faces next to each wall.\n\nThe continuation changes only $\\rho_{\\mathrm{sf}}$ at faces 0-2 and $\\rho_{\\mathrm{ref}}$ at cells 0-1 next to each\nclamped wall (and their ghost rows); $p_{\\mathrm{sf}}$, $p_{\\mathrm{ref}}$ and the rest balance are untouched. It\napplies with `SNAP_WB_REF4` off; with it on, @sec-ch05-wbref4 replaces the density reference with its own cubic wall\nvalues. `balance_column` refuses to run with the clamp off.\n\n*Aliases.* \"wb-wall-clamp\", \"the wall closure\", \"linear/ln closure\". The continuation arrived as three wall-closure\npatches (linear, then ln-linear, then the two branches), kept as raw notes in `sources/team-notes/` and squash-merged\ninto the pin by chengcli/snapy#297.\n\n### Derivation\n\nNotation as in @sec-ch05-refkernel; cells are counted from the wall, $j=0$ the wall cell, and $r_j=\\overline\\rho_j/\\overline p_j$.\n\n#### The repeated wall cell is first order\n\nNear the wall write $r_j=r_0+j\\,a+O(\\Delta x_1^2)$ with $a=r'\\Delta x_1=O(\\Delta x_1)$. Repeating $r_0$ for every\n$j<0$ gives\n\n$$\n\\begin{aligned}\nr^{s}_0 - r_0 &= \\tfrac38\\,a, \\\\\nr^{s}_1 - r_1 &= \\tfrac1{16}\\,a,\n\\end{aligned}\n$$ {#eq-ch05-wallclamp-repeat}\n\nand errors $\\tfrac{23}{32}a$, $\\tfrac7{32}a$, $\\tfrac1{32}a$ and $0$ in the face average $\\tfrac12(r^s_{f-1}+r^s_f)$ at\nfaces 0 to 3 (`[C4]`, exact). Relative to $r$ these are fixed multiples of $(r'/r)\\Delta x_1$, so the face density\nreference is first order at faces 0-2. The even-parity perturbation ghosts (@sec-ch05-wbx1) copy the bias of\n$\\rho'=\\overline\\rho-\\rho_{\\mathrm{ref}}$ into the ghosts, so the solver's face densities there are first order too;\nthe mirror is not the source, the bias in $\\rho_{\\mathrm{ref}}$ is\n(`docs/derivations/wb-ref-wall.md@e894700ff7aee30b52882e5202b16461413780b0` §3).\n\n#### The continuation\n\nPast a clamped wall the binomial reads, $k$ cells beyond the wall,\n\n$$\nr_{-k} =\n\\begin{cases}\nr_0 + k\\,(r_0 - r_1), & r_1 \\le r_0,\\\\\nr_0\\,(r_0/r_1)^{k}, & r_1 > r_0,\n\\end{cases}\n$$ {#eq-ch05-wallclamp-cont}\n\nand $r_0$ if the value is not positive; the top wall is the mirror image. @eq-ch05-wallclamp-cont is\n`hydro_ref_x1_wall_rop`\n([`hydro_ref_x1_impl.h:68-72`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L68-L72)).\nThe binomial reproduces a linear profile exactly, so with the linear branch the $O(a)$ errors of\n@eq-ch05-wallclamp-repeat vanish at faces 0-2; the ln-linear branch differs from it by $O(a^2)$, errors\n$\\tfrac{31}{32}a^2/r_0$, $\\tfrac14a^2/r_0$, $\\tfrac1{32}a^2/r_0$ (`[C5]`, exact series). Either way faces 0-2 keep\nthe interior's $O(\\Delta x_1^2)$, and for constant $r$ the linear branch returns $r_0$ exactly, so an isothermal\ncolumn is unchanged bit for bit.\n\nEach branch is unbounded on one side: the linear one reaches zero when $r$ rises steeply away from the wall\n($r_{-3}=r_0(1-3d)$ with $d=(r_1-r_0)/r_0$), and the ln-linear one diverges when the neighbour is nearly empty. The\ncode takes the branch that stays closer to $r_0$, so for $r_1\\ge0$ the continuation lies in\n$[r_0(r_0/r_1)^k,\\ r_0(1+k)]$ and is positive (`[C6]`, 60000 random samples, none outside).\n\n#### The one-sided cell-pressure rows\n\nThe two wall cells take the cell average of the quintic through the six faces starting at the wall, weights `w6e`\nderived exactly in `[C2]`: $(95/288, 1427/1440, -133/240, 241/720, -173/1440, 3/160)$ for the wall cell and\n$(-3/160, 637/1440, 511/720, -43/240, 77/1440, -11/1440)$ for the next. They keep the sixth order of\n@eq-ch05-refkernel-pref and read no ghost face.\n\n*Exact and truncated.* Exact: the continuation for linear $r$ (linear branch), the rows for a quintic. Second\norder: $\\rho_{\\mathrm{sf}}$ at faces 0-2. The independent rebuild of `[C12]` gives the face-1 error first order with\nthe repeated wall cell (order 1.03) and second order with @eq-ch05-wallclamp-cont (order 2.01), $n_1$ = 32 to 256.\n\n### Numerical method\n\n@fig-ch05-wallclamp-continuation shows the two branches. The clamp applies on a side when the option is on and that\nside is a physical boundary; the continuation additionally needs the wall side to own at least two cells, so that\nonly owned cells are read. The one-sided rows need the block to fit them (at least five interior cells, or a seam at\nthe other end), else the face mean is kept. The rule runs inside the kernel, in every call, on the CPU, CUDA and MPS\npaths alike.\n\n::: {#cell-fig-ch05-wallclamp-continuation .cell execution_count=3}\n\n::: {.cell-output .cell-output-display execution_count=3}\n![rho/p next to a clamped bottom wall (thick black line; ghost side shaded reddish purple), x1 to the right. Sky-blue circles: the three owned cells; dashed blue curve: the true profile; vermillion squares: the repeated wall cell; bluish-green diamonds: the continuation the code uses at one and two cells past the wall. (a) rho/p rises away from the wall, so the ln-linear branch applies; (b) it falls, so the linear branch applies. The repeated value misses the trend in both.](05-well-balanced_files/figure-html/fig-ch05-wallclamp-continuation-output-1.svg){#fig-ch05-wallclamp-continuation fig-alt='Two panels, each with a curve through three circles to the right of a thick wall line and, left of it, squares at the wall value and diamonds that follow the curve\\'s trend.'}\n:::\n:::\n\n\nThe measured effect at the pin is @fig-ch05-wallclamp-order: next to both walls the face density reference falls at\nsecond order and stays below the largest interior error.\n\n::: {#cell-fig-ch05-wallclamp-order .cell execution_count=4}\n\n::: {.cell-output .cell-output-display execution_count=4}\n![Relative error of the face density reference next to the walls and in the interior, polytrope T = 1 - z/2 one pressure scale height deep, against the number of cells. Bluish-green solid circles and dashed squares: first and second face above the bottom wall; orange solid and dashed triangles: first and second face below the top wall; black dotted diamonds: largest interior error. The dotted black line has slope -2. Every series falls at second order.](05-well-balanced_files/figure-html/fig-ch05-wallclamp-order-output-1.svg){#fig-ch05-wallclamp-order fig-alt='Log-log plot of error against cell count 16 to 128 with five falling lines, all parallel to a slope-two guide, the interior line on top.'}\n:::\n:::\n\n\n### Code\n\n| what | code link | symbol | switch |\n|--------|----------|----------|------|\n| the YAML key | [`hydro_options.cpp:57`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_options.cpp#L57) | `wb_wall_clamp` | `dynamics/wb-wall-clamp` |\n| its default | [`hydro.hpp:54`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.hpp#L54) | `wb_wall_clamp` | default `true` |\n| @eq-ch05-wallclamp-cont | [`hydro_ref_x1_impl.h:68-72`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L68-L72) | `hydro_ref_x1_wall_rop` | |\n| continuation inside the binomial | [`hydro_ref_x1_impl.h:91-106`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L91-L106) | `ext_lo` | |\n| clamp gates of the rows | [`hydro_ref_x1_impl.h:132-135`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L132-L135) | `clamp_in` | clamp on, physical side |\n| one-sided rows | [`hydro_ref_x1_impl.h:158-172`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L158-L172) | `w6e` | |\n| ratio range and continuation flags | [`hydro_ref_x1_impl.h:189-192`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L189-L192) | `ext_hi` | two owned cells |\n| MPS tensor path | [`hydro_dispatch.cpp:163-190`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_dispatch.cpp#L163-L190) | `wall_rop` | |\n\n: Code map of the wall clamp and continuation. {#tbl-ch05-wallclamp-code}\n\n1. The option is read from `dynamics` with default `true` as `wb_wall_clamp`\n   ([`hydro_options.cpp:57`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_options.cpp#L57))\n   and passed to the kernel by `_hydro_ref_x1`.\n2. In the cell function, `clamp_in` and `clamp_out` switch the two wall cells to the rows `w6e`\n   ([`hydro_ref_x1_impl.h:158-172`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L158-L172)).\n3. The owned range `jlo`..`jhi` and the flags `ext_lo`, `ext_hi` are set\n   ([`hydro_ref_x1_impl.h:189-192`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L189-L192)),\n   and the binomial replaces each index past the wall by `hydro_ref_x1_wall_rop`\n   ([`hydro_ref_x1_impl.h:91-106`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L91-L106)).\n4. The MPS path applies the same rule to its padded ratio with `wall_rop`\n   ([`hydro_dispatch.cpp:163-190`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_dispatch.cpp#L163-L190)).\n\nAn unknown key in `dynamics` is refused by the key check of the options parser; the clamp itself issues no warning.\n`balance_column` raises if called with the clamp off (@sec-ch05-balcol).\n\n### Tests\n\n| test (ctest name) | what it asserts | tolerance | where the tolerance comes from |\n|----------------|-------------|-----|-----|\n| `tests/test_wb_ref_wall.cpp` (`test_wb_ref_wall.release`), `faces_next_to_the_walls_are_second_order` | observed order $n_1$ 32 $\\to$ 64 of $\\rho_{\\mathrm{sf}}$, $\\rho_L$, $\\rho_R$ at faces 1-2 next to both walls; wall faces within the interior error | order $\\ge1.7$; $\\le1.5\\times$ interior max | below the 1.81-2.12 the closure measures; above the 1.05 of the repeated cell |\n| same, `order_table` | prints the table of @fig-ch05-wallclamp-order | none | report aid |\n| same, `faces_next_to_the_walls_are_second_order_cuda`, `order_table_cuda_matches_cpu` | CUDA orders; CUDA equals CPU | as above; $10^{-13}$ | round-off |\n| `tests/test_face_floor.cpp` (`test_face_floor.release`), `face_floor_fires_on_an_unresolved_column` | dipped-face mass flux with the closure | $2.83191\\times10^{-8}$, $10^{-5}$ relative | pinned value of the closure |\n| `tests/test_hydro_ref_x1.cpp` (`test_hydro_ref_x1.release`) clamp cases | with the clamp, ghosts do not reach the interior | exact | structural |\n| `test_straka_redo` | the straka deck at CFL 1.6 to $t=60$ s exits 0 and redoes at least one step | exit status; output match | robustness of the redo path, not accuracy |\n| this chapter's check | `[C2]`, `[C4]`–`[C6]`, `[C11]`, `[C12]` | per claim | stated in the check |\n\n: Tests of the wall clamp and continuation. {#tbl-ch05-wallclamp-tests}\n\n**Evidence.** At the pin, `test_wb_ref_wall.release` prints the face errors of @fig-ch05-wallclamp-order and the\nobserved orders 2.02, 2.03, 2.03 (bottom face 1: $\\rho_{\\mathrm{sf}}$, $\\rho_L$, $\\rho_R$), 2.03, 2.06, 2.05 (bottom\nface 2), 1.96, 1.81, 1.97 (top face 1) and 1.94, 1.94, 2.12 (top face 2), $n_1$ 32 $\\to$ 64; on the isothermal column\n($\\beta=0$) the wall faces carry no first-order term [sha `e894700ff7aee30b52882e5202b16461413780b0`; deck:\n`tests/test_wb_ref_wall.cpp` `order_table`, polytrope $T=1-\\beta z$, $g=R=1$, one pressure scale height; run:\nctest `test_wb_ref_wall.release`, 2026-10-10, CPU, double, 1 rank; data `src/snapy_report/ch05/data/wb_ref_wall_order.json`].\n`test_face_floor` (all three arms), `test_hydro_ref_x1` and `test_straka_redo` pass in the same run.\nThe check's rebuild reproduces all 40 printed numbers of that table to the printed four digits (`[C11]`). It also\nshows that the test averages its cells over the full-precision column depth but writes `x1max` into the block's YAML\nwith six significant digits, so the block's `dx1f`, which the scan uses, is $4.1\\times10^{-7}$ relatively wider at\n$\\beta=0.5$; with one consistent width the faces next to the bottom wall move by at most $2.6\\times10^{-7}$ in\nrelative error, far below the test's tolerances. The repeated-wall-cell numbers are the check's, not a snapy run:\nface-1 error $2.880\\times10^{-3}$, $1.392\\times10^{-3}$, $6.840\\times10^{-4}$, $3.391\\times10^{-4}$ at $n_1$ = 32 to\n256 (`[C12]`).\n**Coverage.** CPU; the CUDA cases exist and were not run (**pending: a CUDA run at the pin**); the MPS path was not\nrun (no MPS device; the derivation note says the same); multi-rank only through @sec-ch05-seam.\n\n### Limits\n\n::: {.callout-warning title=\"Limits\"}\nThe continuation is in cell index, not in physical spacing, so on a stretched grid the wall faces are not covered by\nthe second-order argument. With `wb-wall-clamp: false`, `balance_column` cannot be used.\n:::\n\n1. **Stretched grids.** The continuation, like the binomial, assumes uniform spacing. Not measured.\n2. **MPS.** The tensor path implements the same rule and is compared with the CPU path only when run on CPU.\n3. **Straka at CFL 1.6.** `test_straka_redo` is a robustness test past the stability limit. The derivation note's\n   ensembles (`docs/derivations/wb-ref-wall.md@e894700ff7aee30b52882e5202b16461413780b0` §5) were measured on the code\n   of the wall-closure commits, not at the pin, and its $\\epsilon=10^{-4}$ ensemble does not separate the references;\n   the near-zero linear continuation as the cause of the linear form's failure there is a hypothesis of that note.\n4. **Stale text in the notes.** `docs/derivations/wb-ref4.md@e894700ff7aee30b52882e5202b16461413780b0` §1 still\n   describes the binomial as edge-replicated at a clamped wall; the code at the pin continues the ratio as above.\n5. **Untested combinations.** See the switch coverage matrix of Chapter 12.\n\n\n## Reference continuity across $x_1$ seams: anchor relay and ghost-row exchange ($x_1$ block split) {#sec-ch05-seam}\n\n<!-- PROVENANCE\npin: snapy@e894700ff7aee30b52882e5202b16461413780b0 (chengcli/snapy)\nsources: OUTLINE.md 5.4; src/hydro/hydro.cpp; src/layout/layout.cpp; tests/test_pref_local_seam.cpp;\n         tests/test_x1_seam_split.cpp; tests/test_x1_seam_split_mp.cpp (re-derived from the code; no derivation note)\nstatus: draft\n-->\n\n### Summary\n\n::: {.callout-note title=\"At a glance\"}\n**What it does.** Makes the reference of a column split into several $x_1$ blocks equal to the reference of one\nblock: the face-pressure scan is relayed from block to block, top down, and the ghost rows of $p_{\\mathrm{ref}}$\nand $\\rho_{\\mathrm{ref}}$ are replaced by the neighbour's interior rows.\n**Switch.** None. On whenever the layout splits $x_1$ ($p_z>1$) and $x_1$ is not periodic.\n**Order.** Exact: a split column has the one-block reference up to the round-off of the chained scan.\n**Defining equation.** @eq-ch05-seam-relay.\n:::\n\nThe reference kernel scans each column from an anchor at the top of the block (@sec-ch05-refkernel). On a column\nsplit into $n_{b1}$ blocks along $x_1$, a block below the top one has no top of the domain to anchor at, and an\nanchor from its own top cell would start a new scan with a different constant: the reference would jump at every\nseam, and that jump would enter $p'=\\overline p-p_{\\mathrm{ref}}$ as a spurious perturbation every step. The relay\npasses the running face pressure down instead, so the scan is one scan across the whole column. The second step\nexchanges the reference's ghost rows, because the block-local quadrature of the ghost cells (one-sided rows, the\n$[\\min,\\max]$ guard) does not reproduce the owner's interior values.\n\nWith both steps, the perturbation field the reconstruction sees is identical on both sides of every seam, so the\ntwo sides compute the same seam-face states, whether the neighbour runs on another process or on another thread of\nthe same one.\n\n*Aliases.* \"the x1 relay\" and \"anchor relay\" in comments; chengcli/snapy#254 (the seam jump), chengcli/snapy#259\n(the in-process relay).\n\n### Derivation\n\nNumber the blocks of one column $b=1..n_{b1}$ from the bottom, and write $i^{(b)}_s$, $i^{(b)}_u$ for the first and\nlast interior cell of block $b$. One block scans @eq-ch05-refkernel-scan downward from its top anchor. For blocks\n$b<n_{b1}$ the anchor is not @eq-ch05-refkernel-anchor but the bottom-face pressure of the block above:\n\n$$\np^{(b)}_{\\mathrm{sf},\\,i^{(b)}_u+1/2} = p^{(b+1)}_{\\mathrm{sf},\\,i^{(b+1)}_s-1/2},\n$$ {#eq-ch05-seam-relay}\n\nand block $n_{b1}$, which owns the domain top, uses @eq-ch05-refkernel-anchor. Since the two faces in\n@eq-ch05-seam-relay are the same physical face, and @eq-ch05-refkernel-scan adds the same terms\n$g\\overline\\rho_i\\Delta x_{1,i}$ in the same order as a single block would, the face pressures of the split column\nequal those of one block up to the round-off of the different summation boundaries. @eq-ch05-seam-relay is\n`take_x1_anchor` in the block below\n([`hydro.cpp:525-533`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L525-L533))\nand `pass_x1_anchor` in the block above\n([`hydro.cpp:577-579`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L577-L579)).\n\nThe cell pressure of a cell near the seam reads six faces, two beyond the cell on each side, so its value in the\nblock that owns it differs from the value the neighbour computes for the same cell in its ghost rows: the\nneighbour has fewer faces there and uses one-sided rows or the face-mean fallback. Overwriting the $n_g$ ghost rows\nof $p_{\\mathrm{ref}}$ and $\\rho_{\\mathrm{ref}}$ with the owner's interior rows makes both blocks hold the owner's value\nfor every cell. Then $p'$ and $\\rho'$ agree cell by cell across the seam, the reconstruction of each side reads the\nsame data in the stencil across the seam, and the seam-face states agree. The exchange is in `_hydro_ref_x1`, with\ntags `kWbGhostUpTag` and `kWbGhostDnTag`\n([`hydro.cpp:593-640`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L593-L640)).\n\n*Exact and truncated.* Nothing is truncated: the split reference equals the one-block reference except for the\nsummation order of the relayed scan. Where the face density of @sec-ch05-wbref4 is used, its cell part runs before\nthis exchange and its face part after it, so the exchanged rows carry the fourth-order cell density and the faces are\ncomputed from them on both sides. There is no executable check; the property is tested by the split-equals-one-block\ntests below.\n\n### Numerical method\n\n@fig-ch05-seam-relay shows the two steps. The relay is serial along the column: each block waits for the block above\nbefore it scans. Across processes the anchor is a point-to-point message (tag `0x7715`); between blocks of one\nprocess it is posted to a board keyed by the receiving block and taken with a five-minute timeout, so local blocks\nmust run concurrently or from the top down. The ghost-row exchange uses the same pairing. Both run once per call of\n`_hydro_ref_x1`, so in every RK stage, before the reconstruction.\n\n::: {#cell-fig-ch05-seam-relay .cell execution_count=5}\n\n::: {.cell-output .cell-output-display execution_count=5}\n![Reference continuity at an x1 seam (dashed reddish-purple line), x1 to the right; the upper block (top row) owns the domain top (thick black line at its right end). The upper block scans from the top (bluish-green arrow along the top) and passes its bottom-face pressure (orange triangle) down as the lower block's anchor (bluish-green vertical arrow). Then each block's hatched ghost cells of p_ref and rho_ref are overwritten with the neighbour's interior rows (dashed reddish-purple arrows).](05-well-balanced_files/figure-html/fig-ch05-seam-relay-output-1.svg){#fig-ch05-seam-relay fig-alt='Two offset rows of cells meeting at a dashed seam line; arrows show a scan along the top row, an anchor passed down at the seam, and copies between interior cells and the hatched ghost cells of the other row.'}\n:::\n:::\n\n\nTwo related seam mechanisms belong to other sections: the single-valued seam flux average across process seams\n(Chapter 4) and, under `SNAP_X1_CENTROID_EXACT`, the exchange of plain-mean and face-pressure ghost rows\n(@sec-ch05-x1cent).\n\n### Code\n\n| what | code link | symbol | switch |\n|--------|----------|----------|------|\n| split test and anchor receive | [`hydro.cpp:525-533`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L525-L533) | `x1_split` | $p_z>1$, not periodic |\n| anchor pass | [`hydro.cpp:577-579`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L577-L579) | `pass_x1_anchor` | |\n| ghost-row exchange | [`hydro.cpp:593-640`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L593-L640) | `kWbGhostUpTag` | |\n| receive, remote or local | [`layout.cpp:879-905`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/layout/layout.cpp#L879-L905) | `take_x1_anchor` | |\n| send, remote or local | [`layout.cpp:907-922`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/layout/layout.cpp#L907-L922) | `pass_x1_anchor` | |\n| the scan reading the anchor | [`hydro_ref_x1_impl.h:30-38`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L30-L38) | `anchor` | |\n\n: Code map of reference continuity across $x_1$ seams. {#tbl-ch05-seam-code}\n\n1. `_hydro_ref_x1` sets `x1_split` from the layout and, if set, receives the anchor from the block above with\n   `take_x1_anchor`; with no block above the anchor is empty and the kernel builds its own\n   ([`hydro.cpp:525-533`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L525-L533)).\n2. The kernel scans from the received `anchor`\n   ([`hydro_ref_x1_impl.h:30-38`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_ref_x1_impl.h#L30-L38));\n   the cell part of @sec-ch05-wbref4 follows.\n3. The block's bottom-face pressure goes to the block below with `pass_x1_anchor`\n   ([`hydro.cpp:577-579`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L577-L579)).\n4. The interior rows go up and down with `kWbGhostUpTag` and `kWbGhostDnTag`, and the received rows overwrite the\n   ghost rows\n   ([`hydro.cpp:593-640`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L593-L640)).\n5. The face part of @sec-ch05-wbref4 runs last.\n\nA local anchor that does not arrive within five minutes raises the error of `take_x1_anchor`\n([`layout.cpp:879-905`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/layout/layout.cpp#L879-L905)),\nthe only error a user can hit here.\n\n### Tests\n\n| test (ctest name) | what it asserts | tolerance | where the tolerance comes from |\n|----------------|-------------|-----|-----|\n| `tests/test_pref_local_seam.cpp` (`test_pref_local_seam.release`), `local_blocks_restart_the_reference_at_the_seam` | $p_{\\mathrm{ref}}$ of the cells either side of the seam equals the one-block value | $10^{-6}$ abs | chained-scan round-off |\n| same, `in_process_split_matches_one_block_after_200_steps` | four in-process blocks equal one block after 200 steps | $10^{-12}$ relative | measured $5.4\\times10^{-14}$ in $v_1$ (test comment) |\n| `tests/test_x1_seam_split.cpp` arms `_x1_centroid`, `_wb_ref4`, `_radial_exact`, `_radial_exact_off` | a split column equals one block after 20 steps, full and hydrostatic-split pressure | $10^{-13}$ | round-off |\n| `tests/test_x1_seam_split_mp.cpp` (2 ranks) and its arms | two ranks equal two in-process blocks and one block | $10^{-13}$ | round-off |\n\n: Tests of reference continuity across seams. {#tbl-ch05-seam-tests}\n\n**Evidence.** All pass at the pin [sha `e894700ff7aee30b52882e5202b16461413780b0`; decks: the test files; run:\n`ctest -V`, Release build, 2026-10-10, CPU, double; 1 rank, the `_mp` entries 2 ranks under `torchrun`]. Printed gaps\nof that run: `_x1_centroid` split against one block $0$ (both `non-hydrostatic` 1 and 0); `_wb_ref4`\n$6.775\\times10^{-15}$ and $1.675\\times10^{-15}$; `_mp` arms, 2 ranks against 2 in-process blocks, $0$ in every arm.\n**Coverage.** CPU, 1 and 2 ranks; CUDA arms exist and were not run (**pending: a CUDA run at the pin**); more than two\nranks along $x_1$ is not tested.\n\n### Limits\n\n1. **Serial relay.** The anchor travels down the column block by block, so the latency of the reference grows with\n   $n_{b1}$. Not measured.\n2. **Periodic $x_1$.** No relay; each block anchors at its own top. A periodic $x_1$ with gravity is not a hydrostatic\n   column anyway.\n3. **Stale test comment.** The header of `tests/test_pref_local_seam.cpp` still says the test is red and does not fix\n   the jump; at the pin both cases pass, after chengcli/snapy#259.\n4. **Untested combinations.** See the switch coverage matrix of Chapter 12.\n\n\n## Hydrostatic mode: gravity replaced by the cell's own pressure difference (`forcing/const-gravity/non-hydrostatic`) {#sec-ch05-hsmode}\n\n<!-- PROVENANCE\npin: snapy@e894700ff7aee30b52882e5202b16461413780b0 (chengcli/snapy)\nsources: OUTLINE.md 5.5; src/hydro/hydro_forward.cpp; src/forcing/const_gravity.cpp;\n         docs/derivations/x1-centroid-spherical.md@e894700ff7aee30b52882e5202b16461413780b0 §4 (re-derived from the code)\nstatus: draft\n-->\n\n### Summary\n\n::: {.callout-note title=\"At a glance\"}\n**What it does.** Replaces the fraction $1-n_h$ of the $x_1$ gravity force $\\rho g_1$ by the difference of the cell's\nown reconstructed face pressures, and books the same replacement in the energy.\n**Switch.** YAML `forcing/const-gravity/non-hydrostatic` $=n_h\\in[0,1]$, default 1 (mode off).\n**Requires.** $g_1\\neq0$. Under `SNAP_X1_CENTROID_EXACT` it uses the $r^2$ operator of @sec-ch05-x1cent.\n**Order.** Exact cancellation at rest; away from rest the force is the difference between Riemann and reconstructed\nface pressures.\n**Defining equation.** @eq-ch05-hsmode-force.\n:::\n\nIn the default, non-hydrostatic mode ($n_h=1$) gravity enters as the body force $\\overline\\rho_ig_1$ of the constant\ngravity forcing, and vertical motion responds to the imbalance between that force and the pressure fluxes. With\n$n_h<1$ part of the body force is replaced by $(p^L_{i+1/2}-p^R_{i-1/2})/\\Delta x_1$, the pressure difference between\nthe cell's own reconstructed states at its upper and lower face. At $n_h=0$ the vertical momentum of a cell then\nchanges only by the jumps $p^{*}-p^{L,R}$ that the Riemann solver introduces at its faces, which vanish in a column\nat rest whatever the column is.\n\nThe value is checked to lie in $[0,1]$ when the YAML is read. The mode is independent of the well-balanced\nreconstruction, but the two are normally used together: the face states it differences are the restored states of\n@eq-ch05-wbx1-split.\n\n*Aliases.* \"hydrostatic-split pressure\", \"nh\" in tests; `rho_grav` in the code.\n\n### Derivation\n\nUnits as in @sec-ch05-wbx1. The constant gravity forcing adds $n_h\\overline\\rho_ig_1$ to the momentum and\n$n_h\\overline\\rho_i\\overline v_{1,i}g_1$ to the energy. The hydrostatic mode adds, in Cartesian geometry,\n\n$$\n\\begin{aligned}\nG_i &= \\frac{p^{L}_{i+1/2} - p^{R}_{i-1/2}}{\\Delta x_{1,i}}, \\\\\n\\Delta(\\rho v_1)_i &= \\Delta t\\,(1-n_h)\\,G_i, \\\\\n\\Delta E_i &= \\Delta t\\,(1-n_h)\\,\\overline v_{1,i}\\,G_i,\n\\end{aligned}\n$$ {#eq-ch05-hsmode-force}\n\nwith $p^{L}_{i+1/2}$ the left state at the upper face and $p^{R}_{i-1/2}$ the right state at the lower face, both\nbelonging to cell $i$. $G$ is `rho_grav`\n([`hydro_forward.cpp:389-397`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L389-L397)),\napplied by the increments that use `non_hydrostatic`\n([`hydro_forward.cpp:901-906`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L901-L906)).\nAt $n_h=0$ the momentum balance of cell $i$ becomes\n\n$$\n\\frac{\\mathrm{d}}{\\mathrm{d}t}(\\overline{\\rho v_1})_i = -\\frac{\\Delta_i[\\rho v_1^2]}{\\Delta x_1}\n- \\frac{(p^{*}-p^{L})_{i+1/2} - (p^{*}-p^{R})_{i-1/2}}{\\Delta x_1} ,\n$$\n\nso the cell's own pressure difference no longer drives it; only the face jumps do. At rest the two states of every\nface agree and $p^{*}=p^{L}=p^{R}$, so the force vanishes exactly for any column, balanced or not (`[C19]`). For\n$0<n_h<1$ the force is the blend of the two forms.\n\nUnder `SNAP_X1_CENTROID_EXACT` on spherical-polar grids the pressure force is\n$-(A_{i+1/2}p^{*}_{i+1/2}-A_{i-1/2}p^{*}_{i-1/2})/V_i+S_i$ with the source $S_i$ of @eq-ch05-x1cent-source, and $G$ takes\nthe same operator on the cell's own states,\n$G_i=(A_{i+1/2}p^{L}_{i+1/2}-A_{i-1/2}p^{R}_{i-1/2})/V_i-S_i$, so the two cancel at rest again\n(`docs/derivations/x1-centroid-spherical.md@e894700ff7aee30b52882e5202b16461413780b0` §4). This form is the branch\nthat calls `x1_pressure_source`\n([`hydro_forward.cpp:515-539`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L515-L539)).\n\n*Exact and truncated.* Exact: the cancellation at rest, in both forms. Away from rest the momentum source has the\naccuracy of $p^{*}-p^{L,R}$, which depends on the reconstruction and the Riemann solver (Chapter 4).\n\n### Numerical method\n\n@fig-ch05-hsmode-cell shows the quantities. $G$ is formed right after the $x_1$ reconstruction (and the\nimmersed-solid face treatment), from the interior faces of each cell, and applied once per stage together with the\nother source increments of `HydroImpl::forward`. It is explicit. The energy row books $\\overline v_1G$, and the\ngravity-work bookkeeping of Chapter 6 counts the same term (`original_gravity_work`).\n\n::: {#cell-fig-ch05-hsmode-cell .cell execution_count=6}\n\n::: {.cell-output .cell-output-display execution_count=6}\n![Hydrostatic mode in one cell, x1 upward. Orange triangles: the cell's own reconstructed face pressures, the left state at its upper face and the right state at its lower face; orange arrows: the Riemann face pressures p* at both faces. The vermillion arrow is the fraction (1 - n_h) of the body force that is removed, the bluish-green arrow the difference of the cell's own face pressures that replaces it.](05-well-balanced_files/figure-html/fig-ch05-hsmode-cell-output-1.svg){#fig-ch05-hsmode-cell fig-alt='A single shaded cell with triangles at its top and bottom face, arrows through both faces, and two vertical arrows of opposite direction beside it.'}\n:::\n:::\n\n\n### Code\n\n| what | code link | symbol | switch |\n|--------|----------|----------|------|\n| the key, default and range | [`const_gravity.cpp:25-26`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/forcing/const_gravity.cpp#L25-L26) | `non_hydrostatic` | default 1 |\n| the remaining body force | [`const_gravity.cpp:46-52`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/forcing/const_gravity.cpp#L46-L52) | `forward` | |\n| $G$, Cartesian form | [`hydro_forward.cpp:389-397`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L389-L397) | `rho_grav` | $n_h<1$ |\n| $G$, $r^2$ form | [`hydro_forward.cpp:515-539`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L515-L539) | `x1_pressure_source` | `SNAP_X1_CENTROID_EXACT` |\n| work counted in the gravity-work budget | [`hydro_forward.cpp:850-857`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L850-L857) | `original_gravity_work` | |\n| momentum and energy increments | [`hydro_forward.cpp:901-906`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L901-L906) | `non_hydrostatic` | |\n\n: Code map of the hydrostatic mode. {#tbl-ch05-hsmode-code}\n\n1. The YAML value is read into `non_hydrostatic` with default 1 and checked to lie in $[0,1]$\n   ([`const_gravity.cpp:25-26`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/forcing/const_gravity.cpp#L25-L26)).\n2. `ConstGravityImpl::forward` adds $n_h$ times the body force and its work\n   ([`const_gravity.cpp:46-52`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/forcing/const_gravity.cpp#L46-L52)).\n3. After the $x_1$ reconstruction, `rho_grav` is filled for the interior cells\n   ([`hydro_forward.cpp:389-397`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L389-L397)),\n   and overwritten by the $r^2$ form with `x1_pressure_source` when that switch acts\n   ([`hydro_forward.cpp:515-539`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L515-L539)).\n4. The increments are added with the weight $1-n_h$ read from `non_hydrostatic`\n   ([`hydro_forward.cpp:901-906`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L901-L906)).\n\nA value outside $[0,1]$ fails the `TORCH_CHECK` of step 1. There is no warning.\n\n### Tests\n\n| test (ctest name) | what it asserts | tolerance | where the tolerance comes from |\n|----------------|-------------|-----|-----|\n| `tests/test_hydrostatic.cpp` (`test_hydrostatic.release`), `cubed_sphere_remains_at_rest` | `non-hydrostatic: 0.`; a cubed-sphere hydrostatic atmosphere keeps its vertical velocity below the bound for 100 steps | $10^{-8}$ | round-off margin |\n| `tests/test_x1_centroid_rest.py` (`test_x1_centroid_rest_python`) | rest force at $n_h$ = 1 and 0, with and without the switch | $10^{-10}$ on, $>10^{-8}$ off | @sec-ch05-x1cent |\n| `tests/test_x1_seam_split.cpp`, `tests/test_x1_seam_split_mp.cpp` arms | split equals one block at $n_h$ = 1 and 0 | $10^{-13}$ | round-off |\n| this chapter's check, `[C19]` | cancellation at rest, both forms | $10^{-12}$ | round-off |\n\n: Tests of the hydrostatic mode. {#tbl-ch05-hsmode-tests}\n\n**Evidence.** At the pin, `test_hydrostatic` prints a maximum spurious vertical velocity after 100 steps of\n$7.84\\times10^{-15}$, and the $n_h=0$ rows of `test_x1_centroid_rest` read, switch off and on, $6.0\\times10^{-8}$ and\n$8.3\\times10^{-15}$ (interior, $r_0/H=5$, explicit) [sha `e894700ff7aee30b52882e5202b16461413780b0`; decks: the test\nfiles; run: `ctest -V` and `python tests/test_x1_centroid_rest.py` against the pin's build, 2026-10-10, CPU, double,\n1 rank].\n**Coverage.** CPU; CUDA twins exist and were not run (**pending: a CUDA run at the pin**); 2 ranks through the seam\ntests. No test measures the mode away from rest.\n\n### Limits\n\n1. **Not a hydrostatic model.** $n_h=0$ removes the cell's own pressure difference from the vertical momentum, but\n   the vertical velocity is still prognostic; this is not a hydrostatic primitive-equation solver.\n2. **Gravity-work interplay.** The energy term enters the gravity-work bookkeeping of Chapter 6 through\n   `original_gravity_work`; its interaction with the face forms is described there.\n3. **Untested combinations.** See the switch coverage matrix of Chapter 12.\n\n\n## `balance_column`: projection of a ghost-free column onto the scheme's discrete balance (C++ and Python API) {#sec-ch05-balcol}\n\n<!-- PROVENANCE\npin: snapy@e894700ff7aee30b52882e5202b16461413780b0 (chengcli/snapy)\nsources: OUTLINE.md 5.6; src/hydro/balance_column.cpp; src/hydro/balance_column.hpp; python/csrc/pyhydro.cpp;\n         examples/bryan.cpp; tests/test_balance_column.cpp; tests/run_bryan_balance_ic.cmake (re-derived from the code)\nstatus: draft\n-->\n\n### Summary\n\n::: {.callout-note title=\"At a glance\"}\n**What it does.** Moves a column of cell averages, at fixed $p/\\rho$ per cell, to the fixed point\n$\\overline p=p_{\\mathrm{ref}}(\\overline p)+C$ of @eq-ch05-wbx1-rest, so that the solver starts it at rest.\n**Switch.** None: an API function, `balance_column` in C++ and in the Python package, called by initial-condition\nbuilders. Requires `wb-wall-clamp` on, at least five cells, positive $p$ and $\\rho$.\n**Order.** Fixed point to a residual below `rtol` (default $10^{-10}$, at most 120 sweeps).\n**Defining equation.** @eq-ch05-balcol-iter.\n:::\n\nA column integrated from the continuum hydrostatic equation is balanced to the truncation error of that integration,\nnot to the scheme's own discrete balance. The well-balanced reconstruction then sees a perturbation $p'$ that is not\nconstant and turns its variation into a standing force on an atmosphere that should be at rest. `balance_column`\nremoves that force before the run starts: it iterates the column onto the discrete rest state, holding the\ntemperature of each cell fixed for ideal mixtures, and returns the balanced column, the residual and the number of\nupdates. The fixed point is defined only up to a free constant $C$, so the column moves; any pinned quantity (surface\npressure, column mass) has to be re-pinned by the caller.\n\nUnder `SNAP_WB_REF4` on a non-uniform grid it iterates against the switched cell pressure, which is the fixed point\nthe solver then enforces. Under `SNAP_X1_CENTROID_EXACT` it balances only a column declared Cartesian.\n\n*Aliases.* \"the balance-ic projection\" (the bryan example's `balance-ic`), chengcli/snapy#250 D1.\n\n### Derivation\n\nUnits as in @sec-ch05-wbx1. Let the column hold $n_1\\ge5$ cells with no ghosts and both ends physical, and let\n$\\theta_i=\\overline p_i/\\overline\\rho_i$ be taken once from the input. One sweep evaluates the reference kernel on the\nwhole column, reads the gauge at the top cell and updates\n\n$$\n\\begin{aligned}\nC &= \\overline{p}_{n_1-1} - p_{\\mathrm{ref},n_1-1}, \\\\\n\\overline{p}_i &\\leftarrow p_{\\mathrm{ref},i}(\\overline{p},\\overline{\\rho}) + C, \\\\\n\\overline{\\rho}_i &\\leftarrow \\overline{p}_i/\\theta_i ,\n\\end{aligned}\n$$ {#eq-ch05-balcol-iter}\n\nand stops when\n\n$$\n\\varepsilon = \\max_i\\frac{\\lvert \\overline{p}_i - p_{\\mathrm{ref},i} - C\\rvert}{\\overline{\\rho}_i\\,g\\,\\Delta x_{1,i}} < \\mathrm{rtol} .\n$$ {#eq-ch05-balcol-res}\n\n@eq-ch05-balcol-iter and @eq-ch05-balcol-res are the loop that calls `call_hydro_ref_x1`\n([`balance_column.cpp:85-104`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L85-L104)).\nA fixed point of @eq-ch05-balcol-iter satisfies @eq-ch05-wbx1-rest with $c=C$, so it is at rest in the solver. The\nresidual is checked before the update, so the returned column is the one it describes and an already balanced\ncolumn comes back after zero updates. $\\varepsilon$ bounds the residual acceleration in units of $g$: a perturbation\ndifference $\\delta p'$ across a cell drives an acceleration $\\delta p'/(\\overline\\rho\\Delta x_1)$.\n\nThe gauge is read at the top cell, where the pressure is lowest, so the column moves least where it is thinnest; the\ncode comment records that a gauge at the bottom diverges on a deep column. Holding $\\theta_i$ fixed holds the\ntemperature fixed for `ideal-gas` and for `ideal-moist` at fixed mass fractions. No convergence proof exists; the\nsweep is a contraction in practice, and the check shows it on a column that is not balanced to begin with\n(`[C15]`: a $\\beta=0.3$ polytrope with a $10^{-3}$ pressure bump at fixed $p/\\rho$, $n_1=64$, residual\n$4.64\\times10^{-2}$ to $1.03\\times10^{-11}$ in 12 updates, $p/\\rho$ unchanged to $1.5\\times10^{-16}$).\n\n*Why the result transfers to the blocks.* With the wall clamp on, the reference of a block's interior reads only owned\ncells at a physical wall (@sec-ch05-wallclamp), so a ghost-free column and a block holding the same cells get the same\n$p_{\\mathrm{ref}}$, bitwise; that is what the first test below asserts. Without the clamp the wall rows read ghost\nfaces that the ghost-free column does not have, and the two disagree, which is why the function refuses to run.\n$\\rho_{\\mathrm{sf}}$ differs at the bottom cell only (its fallback keys on the array index), and it plays no part in\nthe fixed point.\n\n*Exact and truncated.* The returned column satisfies @eq-ch05-wbx1-rest to $\\varepsilon<\\mathrm{rtol}$; nothing is\ntruncated beyond that.\n\n### Numerical method\n\n@fig-ch05-balcol-gauge shows what the projection does. Each sweep is one call of the reference kernel on the column\n(CPU, CUDA or MPS, with the column's device), plus the switched cell pressure of @sec-ch05-wbref4 when that switch is on\nand the column is non-uniform; uniformity is decided with the solver's test on the column's own widths.\n\n::: {#cell-fig-ch05-balcol-gauge .cell execution_count=7}\n\n::: {.cell-output .cell-output-display execution_count=7}\n![What balance_column does to a column, x1 to the right. Vermillion dashed circles: the perturbation p - p_ref of a column marched from the continuum equation, which varies along the column; bluish-green squares: after the projection it is one constant C, the value at the top cell. The column itself moves by C everywhere. Illustrative values.](05-well-balanced_files/figure-html/fig-ch05-balcol-gauge-output-1.svg){#fig-ch05-balcol-gauge fig-alt='Line plot of a wavy dashed curve of circles and a flat line of squares meeting at the right end, with an arrow labelling the right end as the gauge.'}\n:::\n:::\n\n\nA moist initial condition needs one more loop. The projection holds the mass fractions fixed, and the run's first\nsaturation adjustment moves the column off the balance again. The bryan example's `balance-ic` therefore alternates\nsaturation and projection until saturation no longer moves the projected column (relative density change at most\n$4\\epsilon_{\\mathrm{mach}}$ and $\\max\\lvert\\Delta p/p\\rvert\\le10^{-13}$), within `balance-ic-passes`\n(@fig-ch05-balcol-passes).\n\n::: {#cell-fig-ch05-balcol-passes .cell execution_count=8}\n\n::: {.cell-output .cell-output-display execution_count=8}\n![The moist balance-ic loop of the bryan example, per pass. (a) Largest relative pressure change the saturation adjustment makes to the column just projected (bluish-green circles); the dotted line is the stop criterion 1e-13. (b) Projection sweeps balance_column needed in that pass (black squares). The change falls by about a factor 20 per pass and the loop stops after pass 6.](05-well-balanced_files/figure-html/fig-ch05-balcol-passes-output-1.svg){#fig-ch05-balcol-passes fig-alt='Two panels: a semilog plot falling linearly over six passes below a dotted threshold line, and a plot of sweeps falling from 13 to 4.'}\n:::\n:::\n\n\n### Code\n\n| what | code link | symbol | switch |\n|--------|----------|----------|------|\n| refusals: gravity, shape, clamp, geometry | [`balance_column.cpp:18-40`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L18-L40) | `TORCH_CHECK` | `wall_clamp` |\n| at least five cells, positive state | [`balance_column.cpp:42-55`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L42-L55) | `nc1` | |\n| uniform test and switched pressure | [`balance_column.cpp:65-79`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L65-L79) | `ref4` | `SNAP_WB_REF4` |\n| the sweep loop | [`balance_column.cpp:85-104`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L85-L104) | `sweeps` | `rtol`, `max_iter` |\n| failure to converge | [`balance_column.cpp:106-108`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L106-L108) | `err` | |\n| declaration and defaults | [`balance_column.hpp:103-106`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.hpp#L103-L106) | `balance_column` | |\n| Python binding | [`pyhydro.cpp:49-64`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/python/csrc/pyhydro.cpp#L49-L64) | `balance_column` | |\n| moist caller | [`bryan.cpp:221-262`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/examples/bryan.cpp#L221-L262) | `balance_ic` | `balance-ic` |\n\n: Code map of `balance_column`. {#tbl-ch05-balcol-code}\n\n1. The arguments are checked: $g>0$, shape, matching widths, positive `rtol` and `max_iter`, the clamp, and the\n   geometry under `SNAP_X1_CENTROID_EXACT`, each with a `TORCH_CHECK`\n   ([`balance_column.cpp:18-40`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L18-L40)).\n2. The column length `nc1` must be at least 5 and $p$, $\\rho$ positive; $\\theta_i$ is stored\n   ([`balance_column.cpp:42-55`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L42-L55)).\n3. Uniformity is decided and, for a switched non-uniform column, the stencils of @sec-ch05-wbref4 are built into\n   the flag `ref4`\n   ([`balance_column.cpp:65-79`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L65-L79)).\n4. The loop runs @eq-ch05-balcol-res and @eq-ch05-balcol-iter, counting `sweeps`, and raises if the pressure turns\n   non-positive\n   ([`balance_column.cpp:85-104`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L85-L104)).\n5. A residual `err` still above `rtol` raises\n   ([`balance_column.cpp:106-108`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L106-L108)).\n\nErrors a user can hit: the clamp off, fewer than five cells, a non-positive input, a spherical-polar geometry under\n`SNAP_X1_CENTROID_EXACT`, a diverging column, and no convergence within `max_iter`. The caller also owns four\nconditions the function cannot check, listed in its header: physical $x_1$ ends, at least five cells per block of the\nlater run, the same uniform classification in every block, and the saturation loop for moist columns.\n\n### Tests\n\n| test (ctest name) | what it asserts | tolerance | where the tolerance comes from |\n|----------------|-------------|-----|-----|\n| `tests/test_balance_column.cpp` (`test_balance_column.release`), `a_ghost_free_column_reproduces_a_blocks_own_reference` | the column's $p_{\\mathrm{ref}}$, $\\rho_{\\mathrm{ref}}$ equal the block's | bitwise ($\\rho_{\\mathrm{sf}}$ except the bottom cell) | the transfer property |\n| same, `without_the_clamp_the_two_references_disagree` | the control | $>10^{-4}$ before; $<\\mathrm{rtol}$ after | non-vacuity |\n| same, `a_marched_column_comes_out_at_rest` | a marched column, projected, does not move | residual $<10^{-10}$ | `rtol` |\n| same, `the_last_allowed_update_can_converge` | convergence on the last allowed sweep is accepted (chengcli/snapy#278, chengcli/snapy#279) | $10^{-10}$ | `rtol` |\n| same, `the_temperature_and_every_other_channel_stay_put` | $p/\\rho$ unchanged, other rows untouched | $10^{-14}$ relative | round-off |\n| same, `a_balanced_column_is_a_fixed_point`, `a_block_thinner_than_its_ghosts_keeps_its_columns_apart`, `it_refuses_what_it_cannot_deliver` | zero updates on a balanced column; column independence; refusals | exact | contract |\n| same, `x1_centroid_switch_implies_the_ref4_predicate`, `x1_centroid_switch_balances_only_a_cartesian_column` | switch predicates and the geometry refusal | exact | contract |\n| same, `a_moist_column_with_one_condensable_comes_out_at_rest` | moist column balanced and at rest after one step | $<10^{-10}$; marched $>10^{-6}$ | `rtol`; non-vacuity |\n| `test_balance_column_wb_ref4`, `test_balance_column_x1_centroid` | the same tests with each switch set | as above | as above |\n| `test_bryan_balance_ic` | one allowed pass fails with the cap error; the default converges; the dry case projects once | exit status, output match | contract |\n\n: Tests of `balance_column`. {#tbl-ch05-balcol-tests}\n\n**Evidence.** All pass at the pin. The moist test prints audit residual $3.357\\times10^{-1}$ before and\n$8.896\\times10^{-11}$ after, in 13 sweeps, and $\\max\\lvert v_1\\rvert/(g\\Delta t)$ after one step $2.58\\times10^{-11}$\nbalanced against $2.05\\times10^{-2}$ marched, identical in all three arms. The bryan default case stops after pass 6\nwith saturation changes falling from $8.76\\times10^{-8}$ to $1.39\\times10^{-14}$ (@fig-ch05-balcol-passes)\n[sha `e894700ff7aee30b52882e5202b16461413780b0`; decks: `tests/test_balance_column.cpp`,\n`tests/run_bryan_balance_ic.cmake` on `examples/bryan.cpp`; run: `ctest -V`, Release build, 2026-10-10, CPU, double,\n1 rank; data `src/snapy_report/ch05/data/bryan_balance_ic.json`].\n**Coverage.** CPU; the `_cuda` cases exist and were not run (**pending: a CUDA run at the pin**); no multi-rank case\n(the function works on one column).\n\n### Limits\n\n::: {.callout-warning title=\"Limits\"}\nThe balanced column moves by a free constant: the header of `balance_column.hpp` quotes $2.5\\times10^{-4}$ of $p$ on a Neptune-like column\nand $1.2\\times10^{-2}$ on a 300 km giant-planet one (no deck given; not re-measured). A spherical-polar column cannot be\nbalanced under `SNAP_X1_CENTROID_EXACT`.\n:::\n\n1. **Free gauge.** Nothing ties the result to the input's surface pressure or mass; callers re-pin inside their own\n   loop.\n2. **Classification.** The uniform test is made once for the whole column and must match every block's own test.\n3. **Moist columns.** The caller must iterate with saturation adjustment, as the bryan example does.\n4. **No convergence proof.** Convergence is observed (`[C15]`, the tests), not proven.\n5. **Untested combinations.** See the switch coverage matrix of Chapter 12.\n\n\n## Fourth-order, cell/face-consistent density reference (`SNAP_WB_REF4`) {#sec-ch05-wbref4}\n\n<!-- PROVENANCE\npin: snapy@e894700ff7aee30b52882e5202b16461413780b0 (chengcli/snapy)\nsources: OUTLINE.md 5.7; src/hydro/wb_ref4.cpp; src/hydro/hydro.cpp; src/hydro/balance_column.cpp;\n         docs/derivations/wb-ref4.md@e894700ff7aee30b52882e5202b16461413780b0 §§2-9; sources/gw__NEXTPR_spec_wbref_exact.md\nstatus: draft\n-->\n\n### Summary\n\n::: {.callout-note title=\"At a glance\"}\n**What it does.** Replaces the kernel's density reference by $p_{\\mathrm{ref}}F(\\rho/p)$ with a fourth-order filter\n$F$, and the face density by the face value of that same cell field, so the face-density offset is $O(\\Delta x_1^4)$;\non non-uniform grids it also replaces the cell pressure by a cubic average.\n**Switch.** Environment variable `SNAP_WB_REF4`, read once per process, default off; implied by\n`SNAP_X1_CENTROID_EXACT`. Requires $n_g\\ge3$ (checked at setup).\n**Order.** $\\delta\\rho_f=O(\\Delta x_1^4)$; $p_{\\mathrm{sf}}$ is never changed, so the rest balance is the kernel's.\n**Defining equation.** @eq-ch05-wbref4-dref.\n:::\n\nThe kernel's density reference is second order: the binomial smoothing biases $\\rho/p$ by $\\tfrac{\\Delta x_1^2}{2}r''$,\nand its face density is not the face value of its own cell density, so the solver's face density carries the offset\n@eq-ch05-refkernel-offset. That offset enters the $x_1$ mass flux at linear order and, through it, the gravity work. The\nswitch removes it with two operators: a five-point filter with zero second and third moments, which keeps the\nreference fourth order while still removing the two-cell mode, and a face value taken from the quartic through the\nprimitive of the cell reference, so that face and cell are consistent by construction. On a non-uniform grid it also\nreplaces the log-mean cell pressure by the average of a cubic through four face pressures.\n\nGuards keep the kernel's values wherever the new ones would leave the local range or the column is under-resolved,\nand the cell part runs before the seam exchange of @sec-ch05-seam, the face part after it. With the corrected-PE face\nwork of Chapter 6 on (its default with `gravity-work: face`) the one-step spurious stratification of a neutral column\nconverges at about fourth order with the switch and second order without it.\n\n*Aliases.* \"Leg W\" in `docs/derivations/x1-centroid-spherical.md`; `SNAPY_WB_REF_EXACT` in the specification\n`sources/gw__NEXTPR_spec_wbref_exact.md`; #289 in comments.\n\n### Derivation\n\nNotation as in @sec-ch05-refkernel; indices are cell indices and $r_i=\\overline\\rho_i/\\overline p_i$. The derivation is\n`docs/derivations/wb-ref4.md@e894700ff7aee30b52882e5202b16461413780b0` §§2-7, re-written here and checked by\n`[C3]`, `[C7]`, `[C8]`, `[C14]`.\n\n#### Cell density\n\n$$\n\\begin{aligned}\n\\rho_{\\mathrm{ref},i} &= p_{\\mathrm{ref},i}\\,(Fr)_i, \\\\\nF &= \\tfrac1{16}(-1,\\,4,\\,10,\\,4,\\,-1).\n\\end{aligned}\n$$ {#eq-ch05-wbref4-dref}\n\n$F$ has unit sum, zero first, second and third moments and fourth moment $-\\tfrac32$ in cell units, and zero response\nat $k\\Delta x_1=\\pi$ (`[C3]`), so $Fq=q+O(\\Delta x_1^4)$ and the two-cell mode is still removed; its reach, $\\pm2$, is\nthe binomial's, so ghost depth and seam exchange are unchanged. With $p_{\\mathrm{ref}}=\\overline p+c+O(\\Delta x_1^6)$\n(@sec-ch05-refkernel) the cell reference is $\\overline\\rho+cR+O(\\Delta x_1^4)$, and the smooth $cR$ is carried\nconsistently by the face value below. @eq-ch05-wbref4-dref is built in `wb_ref4_stencils` as the filter row `F`\n([`wb_ref4.cpp:120-158`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L120-L158))\nand applied in `wb_ref4_cells` as `fr`\n([`wb_ref4.cpp:263-272`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L263-L272)).\n\nAt a clamped wall the two values past the wall are cubic extrapolations of the four owned cells nearest it,\n$r_0..r_3$ counted from the wall:\n\n$$\n\\begin{aligned}\nr_{-1} &= 4r_0 - 6r_1 + 4r_2 - r_3, \\\\\nr_{-2} &= 10r_0 - 20r_1 + 15r_2 - 4r_3 .\n\\end{aligned}\n$$ {#eq-ch05-wbref4-cubic}\n\nAll five stencil values of the first two cells then lie on one cubic, which $F$ reproduces, so $(Fr)_0=r_0$ and\n$(Fr)_1=r_1$ for any data (`[C7]`): filtering with these wall values and leaving the two end cells unfiltered are the\nsame reference. Ghosts are never read.\n\n#### Face density\n\n$$\n\\begin{aligned}\n\\rho_{\\mathrm{sf},f} &= P'(x_{1,f}), \\\\\nP(x_{1,s+j}) &= \\sum_{k<j}\\rho_{\\mathrm{ref},s+k}\\,\\Delta x_{1,s+k},\n\\end{aligned}\n$$ {#eq-ch05-wbref4-face}\n\nwith $P$ the quartic through the primitive at the five faces $j=0..4$ (four cells), window $s=f-2$ kept inside the owned cells at a\nclamped wall, physical spacing. On a uniform grid the weights on $\\rho_{\\mathrm{ref},s..s+3}$ are $(-1,7,7,-1)/12$ in the\ninterior, $(25,-23,13,-3)/12$ at the wall face and $(3,13,-5,1)/12$ at the next (`[C8]`). The face is exact for cubic\npoint profiles on any grid, so $\\delta\\rho_f=\\rho_{\\mathrm{sf}}-\\mathcal R[\\rho_{\\mathrm{ref}}]=O(\\Delta x_1^4)$ (`[C14]`:\nmid-column offset $3.2\\times10^{-12}$ to $2.8\\times10^{-16}$ relative from $n_1$ = 32 to 256, fitted order 4.68, against\norder 2.00 for the kernel). @eq-ch05-wbref4-face is built as the weights `awt`\n([`wb_ref4.cpp:195-221`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L195-L221))\nand applied by `wb_ref4_faces`\n([`wb_ref4.cpp:276-286`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L276-L286)).\n\n#### Non-uniform cell pressure\n\nOn a non-uniform grid the cell pressure becomes the cell average of the cubic $\\tilde p$ through the face pressures at\nfaces $i-1..i+2$ (window inside the owned faces at a clamped wall), by three-point Gauss-Legendre, exact for a cubic:\n\n$$\np_{\\mathrm{ref},i} = \\frac{1}{\\Delta x_{1,i}}\\int_{x_{1,i-1/2}}^{x_{1,i+1/2}}\\tilde p\\,\\mathrm{d}x_1\n= \\sum_{q=1}^{3}\\frac{w_q}{2}\\,\\tilde p\\big(x_{1,i}+\\xi_q\\tfrac{\\Delta x_{1,i}}{2}\\big),\n$$ {#eq-ch05-wbref4-pnu}\n\nwith nodes $\\xi_q=0,\\pm\\sqrt{3/5}$ and weights $w_q=8/9,5/9$, the non-uniform branch of `wb_ref4_stencils` with the Gauss weights `gw`\n([`wb_ref4.cpp:165-193`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L165-L193)).\nA value outside the cell's two face pressures keeps the log-mean. This moves the discrete fixed point of a non-uniform\ncolumn by $O(\\Delta x_1^2)$, so `balance_column` iterates against it (@sec-ch05-balcol). On a uniform grid the\nsix-face $p_{\\mathrm{ref}}$ is kept.\n\n#### Guards and rest balance\n\nA cell whose $(Fr)_i$ lies outside $[\\min,\\max]$ of $r$ over cells $i-1..i+1$, with relative margin $10^{-10}$, keeps the\nkernel's ratio; a face outside its two neighbouring cell references keeps the kernel's face. A cell with\n$\\lvert\\ln(p_{\\mathrm{sf},i-1/2}/p_{\\mathrm{sf},i+1/2})\\rvert>0.5$, fewer than two cells per pressure scale height, is\nflagged, the flag is dilated by two cells, and flagged cells and faces next to them keep the kernel's values; ghosts\npast a clamped wall do not count. The flag reads $p_{\\mathrm{sf}}$ at most three cells away, which is why $n_g\\ge3$ is\nrequired: then both sides of an $x_1$ seam compute the same flag. The threshold, dilation and margin are design\nchoices, not derived. Since $p_{\\mathrm{sf}}$ is never changed and on a uniform grid neither is $p_{\\mathrm{ref}}$, the\nrest state @eq-ch05-wbx1-rest is the kernel's.\n\n*Exact and truncated.* Exact: the end-cell identity, the face weights for cubics, @eq-ch05-wbref4-pnu for cubics.\n$O(\\Delta x_1^4)$: $\\rho_{\\mathrm{ref}}$ and $\\delta\\rho_f$ in the interior. At the three faces next to a wall the note\ngives $O(\\Delta x_1^3)$ (the anchor constant through the even ghosts); not re-checked here.\n\n### Numerical method\n\n@fig-ch05-wbref4-stencils shows the stencils. The stencils and weights are built once per block, on the CPU in double\nprecision, and cached until device or dtype changes; application is a gather and a weighted sum on the block's device.\nThe cell part runs right after the kernel in `_hydro_ref_x1`, before the seam ghost-row exchange; the face part runs\nafter it, so a column split along $x_1$ gets the same faces as one block. A block with a clamped wall and fewer than\nfour owned cells keeps the kernel's reference.\n\n::: {#cell-fig-ch05-wbref4-stencils .cell execution_count=9}\n\n::: {.cell-output .cell-output-display execution_count=9}\n![The SNAP_WB_REF4 stencils at a bottom wall (thick black line), x1 to the right. Top: the filter F on the wall cell i_s reads two values past the wall (bluish-green diamonds E_1, E_2), which are cubic extrapolations of the four owned cells nearest it (sky-blue circles), never the hatched ghosts; with them the filtered ratio equals r in the end cell. Bottom: the face density at the wall face from the quartic primitive over the four owned cells next to the wall (orange triangles at the five faces); interior faces use the centred weights (-1, 7, 7, -1)/12.](05-well-balanced_files/figure-html/fig-ch05-wbref4-stencils-output-1.svg){#fig-ch05-wbref4-stencils fig-alt='Two rows of cells beside a wall with hatched ghosts; in the top row diamonds sit in two ghost cells and circles in four interior cells under a bracket of five cells; in the bottom row triangles mark five faces under a bracket of four cells.'}\n:::\n:::\n\n\n**The oracle and the measured order.** The test drives a neutral polytrope ($\\gamma=5/3$, $g=m+1$ with\n$m=1/(\\gamma-1)$, $T_0=1+L_z-z$) seeded with a divergence-free overturning mode of amplitude $10^{-4}$, takes one RK3\nstep, and measures $N^2_{\\mathrm{eff}}=\\tfrac g\\gamma\\sum_i(-\\delta s_i)w_i/\\sum_iw_i^2$ from the entropy tendency of the mode\nminus that of the rest state. For this column the exact cell-average tendencies vanish at linear order, so every\n$N^2_{\\mathrm{eff}}$ is scheme error. @fig-ch05-wbref4-order shows the four arms measured at the pin.\n\n::: {#cell-fig-ch05-wbref4-order .cell execution_count=10}\n\n::: {.cell-output .cell-output-display execution_count=10}\n![One-step spurious stratification |N2_eff| n1^2 of a neutral column against the number of cells, (a) 1 and (b) 3 pressure e-folds deep. Vermillion circles: SNAP_WB_REF4 off; bluish-green squares: on. Solid lines: the corrected-PE face work at its default (on); dotted lines with open markers: SNAP_GRAVITY_WORK_RADIAL_EXACT=0. A flat line is second-order convergence of N2_eff; the black dotted guide has slope -2, i.e. fourth order. With the default gravity work the switch takes the error from second to fourth order.](05-well-balanced_files/figure-html/fig-ch05-wbref4-order-output-1.svg){#fig-ch05-wbref4-order fig-alt='Two log-log panels with four lines each: two nearly flat vermillion lines, a steeply falling solid green line and a less steep dotted green line.'}\n:::\n:::\n\n\nWith the corrected-PE face work at its default, the observed orders of $\\lvert N^2_{\\mathrm{eff}}\\rvert$ are 4.07, 4.04\n(1 e-fold) and 3.88, 3.94 (3 e-folds) with the switch, and 2.13, 2.04 and 2.21, 2.08 without it. With\n`SNAP_GRAVITY_WORK_RADIAL_EXACT=0` the switched arm returns 2.96, 2.98 and 2.84, 2.92, and its values\n$-0.0707$, $-0.0358$ (1 e-fold, $n_1$ = 64, 128) and $-0.2257$, $-0.1194$ (3 e-folds) equal the table of\n`docs/derivations/wb-ref4.md@e894700ff7aee30b52882e5202b16461413780b0` §9 to the printed digits. The order-3 \"wall\nband\" that note leaves unidentified is therefore removed by the corrected-PE face work: tested here by switching that\nwork off and on with everything else fixed, not derived.\n\n### Code\n\n| what | code link | symbol | switch |\n|--------|----------|----------|------|\n| the switch, implied by the centroid switch | [`wb_ref4.cpp:83-95`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L83-L95) | `wb_ref4_enabled` | `SNAP_WB_REF4` |\n| margin and resolution threshold | [`wb_ref4.cpp:20-25`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L20-L25) | `kMaxLogDrop` | |\n| stencils and weights | [`wb_ref4.cpp:97-231`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L97-L231) | `wb_ref4_stencils` | |\n| cell part and flag | [`wb_ref4.cpp:233-274`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L233-L274) | `wb_ref4_cells` | |\n| face part | [`wb_ref4.cpp:276-286`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L276-L286) | `wb_ref4_faces` | |\n| ghost-depth check | [`hydro.cpp:94-103`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L94-L103) | `wb_ref4_enabled` | $n_g\\ge3$ |\n| calls around the seam exchange | [`hydro.cpp:565-575`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L565-L575) | `wb_ref4_cells` | |\n| face part after the exchange | [`hydro.cpp:642-645`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L642-L645) | `wb_ref4_faces` | |\n| `balance_column` follows it | [`balance_column.cpp:70-79`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/balance_column.cpp#L70-L79) | `wb_ref4_enabled` | non-uniform only |\n\n: Code map of `SNAP_WB_REF4`. {#tbl-ch05-wbref4-code}\n\n1. `wb_ref4_enabled` reads the environment once; values other than empty, `0`, `false`, `off`, `no` turn it on, and\n   `SNAP_X1_CENTROID_EXACT` turns it on too\n   ([`wb_ref4.cpp:83-95`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L83-L95)).\n2. At setup, with gravity on, $n_g<3$ fails the `TORCH_CHECK` that names `wb_ref4_enabled`\n   ([`hydro.cpp:94-103`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L94-L103)).\n3. In `_hydro_ref_x1` the stencils are built once per block and `wb_ref4_cells` replaces $\\rho_{\\mathrm{ref}}$ (and on a\n   non-uniform grid $p_{\\mathrm{ref}}$) and returns the resolution flag\n   ([`hydro.cpp:565-575`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L565-L575)).\n4. After the seam exchange `wb_ref4_faces` replaces $\\rho_{\\mathrm{sf}}$\n   ([`hydro.cpp:642-645`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L642-L645)).\n\nThe only user-facing error is the ghost-depth check of step 2.\n\n### Tests\n\n| test (ctest name) | what it asserts | tolerance | where the tolerance comes from |\n|----------------|-------------|-----|-----|\n| `tests/test_wb_ref4_order.py` (`test_wb_ref4_order_python`) | switch on: order of $\\lvert N^2_{\\mathrm{eff}}\\rvert\\ge2.75$ over both doublings at 1 and 3 e-folds, $n_1$ 32/64/128; off: $<2.5$ at the last doubling | `ORDER_ON 2.75`, `ORDER_OFF 2.5` | set between the measured off (about 2) and on orders; not derived |\n| `tests/test_x1_seam_split.cpp` (`test_x1_seam_split_wb_ref4.release`), `wb_ref4_flag_at_the_seam_split_matches_one_block` | a split column with the flag switching on next to the seam equals one block | $10^{-13}$ | round-off |\n| same (`test_x1_seam_split_wb_ref4_gravity_0.release`) | with gravity off, $n_g=1$ still steps | runs | the check applies with gravity only |\n| `test_x1_seam_split_mp_wb_ref4` (2 ranks) | two ranks equal two blocks and one block | $10^{-13}$ | round-off |\n| `test_balance_column_wb_ref4`, `test_face_floor_wb_ref4` | `balance_column` finds the switched fixed point; switched dipped-face fluxes $-1.19257\\times10^{-7}$ and $0.0303502$ | $10^{-3}$ relative; $10^{-6}$ | pinned values |\n| this chapter's check | `[C3]`, `[C7]`, `[C8]`, `[C14]` | per claim | stated in the check |\n\n: Tests of `SNAP_WB_REF4`. {#tbl-ch05-wbref4-tests}\n\n**Evidence.** $N^2_{\\mathrm{eff}}n_1^2$ at $n_1$ = 32, 64, 128, re-measured at the pin (ISSUES.md item 3): switch off\n$+0.0719$, $+0.0656$, $+0.0640$ (1 e-fold) and $+0.6198$, $+0.5344$, $+0.5060$ (3 e-folds); on $+0.0025$, $+0.0006$,\n$+0.0001$ and $+0.0407$, $+0.0111$, $+0.0029$ [sha `e894700ff7aee30b52882e5202b16461413780b0`; deck:\n`tests/test_wb_ref4_order.py`; run: `python tests/test_wb_ref4_order.py` against the pin's build, 2026-10-10, CPU,\ndouble, 1 rank; data `src/snapy_report/ch05/data/wb_ref4_order.json`]. The `SNAP_GRAVITY_WORK_RADIAL_EXACT=0` arms of\n@fig-ch05-wbref4-order come from a second run of the same script with that variable set. The seam tests print gaps\nof $6.775\\times10^{-15}$ and $1.675\\times10^{-15}$ ($n_h$ = 1, 0) for the split and 0 for two ranks against two blocks.\nThe ctest entry `test_wb_ref4_order_python` itself failed in a first run because the test imported an older\ninstalled snapy instead of the pin's build; run against the pin's build it passes, as above.\n**Coverage.** CPU; the CUDA twin `test_wb_ref4_order_cuda` and the `_cuda` seam arms were not run (**pending: a CUDA\nrun at the pin**); 2 ranks through the `_mp` arm.\n\n### Limits\n\n::: {.callout-warning title=\"Limits\"}\n`SNAP_WB_REF4` needs `nghost` $\\ge3$. It is read once per process, so every block of a run makes the same choice.\n:::\n\n1. **Thresholds not derived.** The $0.5$ resolution threshold, the two-cell dilation and the $10^{-10}$ margin are\n   design choices (`docs/derivations/wb-ref4.md@e894700ff7aee30b52882e5202b16461413780b0` §7).\n2. **Untested at the pin.** Stretched-grid dynamics (only `balance_column` exercises the non-uniform branch),\n   multi-species columns, and seams across more than two ranks.\n3. **Resolution of the order test.** The test grid is $n_1$ = 32/64/128 against 64/128/256 in the note's table, and the\n   threshold `ORDER_ON` 2.75 no longer distinguishes the fourth order measured at the pin from the third order of the\n   note; the test still separates on from off.\n4. **Names.** The specification calls the switch `SNAPY_WB_REF_EXACT`; the code reads `SNAP_WB_REF4`.\n5. **Untested combinations.** See the switch coverage matrix of Chapter 12.\n\n\n## $r^2$-exact $x_1$ maps on spherical-polar grids (`SNAP_X1_CENTROID_EXACT`) {#sec-ch05-x1cent}\n\n<!-- PROVENANCE\npin: snapy@e894700ff7aee30b52882e5202b16461413780b0 (chengcli/snapy)\nsources: OUTLINE.md 5.8; src/coord/x1_centroid.cpp; src/coord/spherical_polar.cpp; src/hydro/hydro_forward.cpp;\n         src/hydro/hydro.cpp; docs/derivations/x1-centroid-spherical.md@e894700ff7aee30b52882e5202b16461413780b0 §§1-5, 7;\n         sources/study__next-1overR_README.md §§0-3\nstatus: draft\n-->\n\n### Summary\n\n::: {.callout-note title=\"At a glance\"}\n**What it does.** On spherical-polar blocks, feeds every $x_1$ map (reconstruction, scan, reference) the plain means\nof the cells instead of their $r^2$ means, and replaces the radial pressure source by the $r$-moment of a quintic, so a\nhydrostatic column of $r^2$ means is balanced to round-off.\n**Switch.** Environment variable `SNAP_X1_CENTROID_EXACT`, read once per process, default off. Implies `SNAP_WB_REF4`.\nRequires $n_g\\ge3$. Acts on `spherical-polar` only.\n**Order.** Conversion exact to degree 4; rest exact for densities of degree $\\le4$.\n**Defining equation.** @eq-ch05-x1cent-source.\n:::\n\nA finite-volume cell on a spherical-polar grid holds the $r^2$ mean of a quantity, whose centroid sits\n$h^2/(6\\overline r)$ above the mid-radius. Every $x_1$ cell-to-face map of the solver, from the WENO weights to the\nscan and the six-face cell pressure, is a formula for plain means. Fed $r^2$ means they are off by $O(h^2/r)$: the face\nvalues, the scan step, and the pressure force, whose plain difference balances gravity only against the wrong scan.\nThe switch converts the inputs of the maps, for the maps only, to plain means with a five-cell stencil exact to degree\n4, and makes the radial pressure force the $r^2$ mean of the gradient of a quintic through six face pressures. The\nreference on plain means is then the Cartesian one, and the switch implies `SNAP_WB_REF4` so that it is fourth order.\n\nOn Cartesian blocks the switch only implies `SNAP_WB_REF4`; on cubed-sphere blocks it does nothing (their $x_{1v}$ is\nthe mid-radius). `balance_column` balances only a column declared Cartesian under it.\n\n*Aliases.* #289 legs (i)-(iii) in comments; \"the centroid switch\".\n\n### Derivation\n\nUnits: $r$ and $h$ [m]; $A_{i\\pm1/2}=r_{i\\pm1/2}^2$ and $V_i=(r_{i+1/2}^3-r_{i-1/2}^3)/3$ are per unit solid angle, as the\ncode forms them. $\\langle q\\rangle_i=V_i^{-1}\\int r^2q\\,\\mathrm{d}r$ is the $r^2$ mean, $\\overline q_i=h_i^{-1}\\int q\\,\\mathrm{d}r$ the plain\nmean, and $x=(r-\\overline r_i)/h_i$ the local coordinate. Re-written from\n`docs/derivations/x1-centroid-spherical.md@e894700ff7aee30b52882e5202b16461413780b0` §§1-5.\n\n#### The defect\n\nExpanding $q$ about the mid-radius,\n\n$$\n\\begin{aligned}\n\\langle q\\rangle_i &= \\overline q_i + \\delta_i\\,q'(\\overline r_i) + O(h^4/\\overline r^2), \\\\\n\\delta_i &= \\frac{2h_i^2\\,\\overline r_i}{h_i^2 + 12\\,\\overline r_i^2} = \\frac{h_i^2}{6\\overline r_i} - \\frac{h_i^4}{72\\,\\overline r_i^3} + \\cdots\n\\end{aligned}\n$$ {#eq-ch05-x1cent-defect}\n\n(`[C18]`, exact). Each uniform-measure map fed $\\langle q\\rangle$ is off by $\\delta q'=O(h^2/r)$; in particular the scan\nstep becomes $gh\\langle\\rho\\rangle$ instead of $g\\int\\rho\\,\\mathrm{d}r=gh\\overline\\rho$, and the perturbation of a resting\ncolumn is $O(h^2/r)$ instead of a constant.\n\n#### Plain means\n\nFor the $x_1$ maps only, each primitive row is replaced by\n\n$$\n\\begin{aligned}\n\\overline q_i &= \\sum_{k=0}^{4} c_{i,k}\\,\\langle q\\rangle_{s_i+k}, \\\\\n\\sum_k c_{i,k}\\,\\langle x^n\\rangle_{s_i+k} &= \\overline{x^n}_i = \\big(1,\\ 0,\\ \\tfrac1{12},\\ 0,\\ \\tfrac1{80}\\big)_n,\n\\end{aligned}\n$$ {#eq-ch05-x1cent-conv}\n\nfor the monomials $n=0..4$, window $s_i=\\max(\\mathrm{lo},\\min(\\mathrm{hi}-4,i-2))$, centred, inside the owned cells at a physical wall and inside the\narray at a seam. The moments are integrated by four-point Gauss-Legendre, exact for degree 6, and the $5\\times5$ system\nis solved once per block. The conversion is exact for degree 4 and not 5, on uniform and stretched grids and in the\nwall windows, and its weights sum to 1 (`[C16]`). @eq-ch05-x1cent-conv is `x1_plain_mean_stencils`\n([`x1_centroid.cpp:104-155`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/x1_centroid.cpp#L104-L155)).\nGhosts past a clamped wall get the mirrored correction of the owned cells, odd for the normal velocity, in\n`x1_plain_means`\n([`x1_centroid.cpp:157-182`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/x1_centroid.cpp#L157-L182));\nat a seam the outer ghosts' windows are off-centre, so their plain means are replaced by the neighbour's.\n\n#### The pressure source\n\nWith $\\tilde p$ the quintic through the six face pressures nearest cell $i$ (window over faces, one-sided at a wall,\nreaching two faces past a seam), the radial pressure source is\n\n$$\nS_i = \\frac{2}{V_i}\\int_{r_{i-1/2}}^{r_{i+1/2}} r\\,\\tilde p\\,\\mathrm{d}r = \\sum_{j=0}^{5}w_{i,j}\\,p^{*}_{s+j},\n$$ {#eq-ch05-x1cent-source}\n\nand integration by parts, with $\\tilde p$ through both faces of the cell, gives\n$-(A_{i+1/2}p^{*}_{i+1/2}-A_{i-1/2}p^{*}_{i-1/2})/V_i+S_i=-V_i^{-1}\\int r^2\\tilde p'\\,\\mathrm{d}r$: the net pressure force is\nthe $r^2$ mean of $-\\partial_r\\tilde p$. A constant pressure gives $S_iV_i=A_{i+1/2}-A_{i-1/2}$ exactly, with $V_i$ in the\ncube form of the cell volume (`[C17]`, both identities in exact rationals). @eq-ch05-x1cent-source is\n`x1_pressure_source_stencils`\n([`x1_centroid.cpp:184-222`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/x1_centroid.cpp#L184-L222)),\nused in place of the plain difference by the branch that tests `exact_x1`\n([`spherical_polar.cpp:251-264`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/spherical_polar.cpp#L251-L264)).\nThe hydrostatic mode takes the same operator (@sec-ch05-hsmode).\n\n#### Rest balance\n\nOn a hydrostatic column of $r^2$ means: the conversion gives $\\overline\\rho$ to $O(h^6/r)$; the scan then gives the\nexact face pressures plus one constant; the reference on plain means is the Cartesian fourth-order one; and the net\nforce $-V^{-1}\\int r^2(\\tilde p'+g\\rho)\\,\\mathrm{d}r$ has the constant drop out. For a density of degree $\\le4$ every step\nis exact and the column is balanced exactly, which is the oracle of the test.\n\n*Exact and truncated.* Exact: the conversion for degree 4, both source identities, rest for degree $\\le4$. For a\nsmooth column the curvature part of the residual is $O(h^6/r)$; what remains is the truncation of the reference itself.\nRatios of means (the Favre velocity, $T=p/\\rho$, $\\rho/p$ inside $F$) are not made exact (@sec-ch05-oneoverr).\n\n### Numerical method\n\n@fig-ch05-x1cent-window shows the windows. In `HydroImpl::forward` the plain-mean view `wx1` is computed before the\nreference, its seam ghost rows are taken from the neighbour, and the reconstruction and the reference read it; the\nprimitives themselves are unchanged. After the Riemann solve the two ghost face pressures each side of a seam are taken\nfrom the neighbour, so the source window is the centred one-block window. Everything runs in every RK stage,\nexplicitly; the stencils are built once per block in double precision.\n\n::: {#cell-fig-ch05-x1cent-window .cell execution_count=11}\n\n::: {.cell-output .cell-output-display execution_count=11}\n![The maps of SNAP_X1_CENTROID_EXACT, x1 = r to the right. Top: a radial cell, its mid-radius (dotted) and its r^2 centroid x1v (bluish-green line) h^2/(6 r) further out. Middle: the five-cell window that converts r^2 means to the plain mean of cell i, centred in the interior and one-sided at the wall (thick black line). Bottom: the six-face window of the pressure source (orange triangles), which reaches two faces past a seam (dashed reddish-purple line) into the neighbour's hatched ghost cells.](05-well-balanced_files/figure-html/fig-ch05-x1cent-window-output-1.svg){#fig-ch05-x1cent-window fig-alt='A single wide cell with two vertical lines inside, below it a row of nine cells with brackets over five cells, and a third row of cells with a dashed seam and six triangles crossing it.'}\n:::\n:::\n\n\n### Code\n\n| what | code link | symbol | switch |\n|--------|----------|----------|------|\n| the switch | [`x1_centroid.cpp:92-102`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/x1_centroid.cpp#L92-L102) | `x1_centroid_exact_enabled` | `SNAP_X1_CENTROID_EXACT` |\n| conversion stencils | [`x1_centroid.cpp:104-155`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/x1_centroid.cpp#L104-L155) | `x1_plain_mean_stencils` | |\n| conversion and mirrored ghosts | [`x1_centroid.cpp:157-182`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/x1_centroid.cpp#L157-L182) | `x1_plain_means` | |\n| source stencils | [`x1_centroid.cpp:184-222`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/x1_centroid.cpp#L184-L222) | `x1_pressure_source_stencils` | |\n| plain-mean view and seam ghosts | [`hydro_forward.cpp:270-285`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L270-L285) | `x1_plain_means` | spherical-polar |\n| ghost face pressures at a seam | [`hydro_forward.cpp:501-508`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L501-L508) | `_x1_ghost_rows` | |\n| the source in the momentum equation | [`spherical_polar.cpp:251-264`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/spherical_polar.cpp#L251-L264) | `x1_pressure_source` | |\n| ghost-row exchange | [`hydro.cpp:270-303`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L270-L303) | `_x1_ghost_rows` | $x_1$ split |\n| implies `SNAP_WB_REF4` | [`wb_ref4.cpp:92-94`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/wb_ref4.cpp#L92-L94) | `x1_centroid_exact_enabled` | |\n\n: Code map of `SNAP_X1_CENTROID_EXACT`. {#tbl-ch05-x1cent-code}\n\n1. `x1_centroid_exact_enabled` reads the environment once\n   ([`x1_centroid.cpp:92-102`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/x1_centroid.cpp#L92-L102)).\n2. On a spherical-polar block `HydroImpl::forward` builds the view with `x1_plain_means` and exchanges its seam ghost\n   rows with `_x1_ghost_rows`\n   ([`hydro_forward.cpp:270-285`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L270-L285)).\n3. The reference and the reconstruction of @sec-ch05-wbx1 read the view; `SNAP_WB_REF4` acts through\n   `wb_ref4_enabled` (@sec-ch05-wbref4).\n4. After the Riemann solve the face-pressure ghost rows are exchanged with `_x1_ghost_rows`\n   ([`hydro_forward.cpp:501-508`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L501-L508)).\n5. `SphericalPolarImpl::forward` adds `x1_pressure_source` in place of the plain-difference correction\n   ([`spherical_polar.cpp:251-264`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/spherical_polar.cpp#L251-L264)).\n\nThe ghost-depth check of @sec-ch05-wbref4 covers this switch, since it implies `SNAP_WB_REF4`; `balance_column` refuses\na non-Cartesian geometry under it. A block too thin for the stencils (`usable` false) keeps the plain path silently.\n\n### Tests\n\n| test (ctest name) | what it asserts | tolerance | where the tolerance comes from |\n|----------------|-------------|-----|-----|\n| `tests/test_x1_centroid_rest.py` (`test_x1_centroid_rest_python`) | linear-density column of $r^2$ means, $r_0/H$ = 5 and 1000, explicit and vertically implicit, $n_h$ = 1 and 0: on, $\\max\\lvert\\rho v_1\\rvert/(\\Delta t\\,g\\rho)<10^{-10}$ in interior and wall cells; off, $>10^{-8}$ at $r_0/H=5$ | `TOL_ON 1e-10`, `TOL_OFF 1e-8` | round-off margin; an ignored switch fails |\n| `tests/test_x1_seam_split.cpp` (`test_x1_seam_split_x1_centroid.release`), `centroid_exact_split_matches_one_block` | split equals one block after 20 steps, $n_h$ = 1 and 0 | $10^{-13}$ | round-off |\n| `test_x1_seam_split_mp_x1_centroid` (2 ranks) | two ranks equal two blocks and one block | $10^{-13}$ | round-off |\n| `test_balance_column_x1_centroid`, `test_face_floor_x1_centroid` | the balance and floor tests with the switch | as in their sections | as there |\n| this chapter's check | `[C16]`–`[C18]` | per claim | stated in the check |\n\n: Tests of `SNAP_X1_CENTROID_EXACT`. {#tbl-ch05-x1cent-tests}\n\n| $r_0/H$ | implicit | $n_h$ | off, interior / wall | on, interior / wall |\n|---|---|---|---|---|\n| 5 | 0 | 1 | $2.377\\times10^{-5}$ / $2.700\\times10^{-5}$ | $2.162\\times10^{-14}$ / $1.547\\times10^{-14}$ |\n| 5 | 0 | 0 | $6.001\\times10^{-8}$ / $7.447\\times10^{-7}$ | $8.347\\times10^{-15}$ / $1.415\\times10^{-14}$ |\n| 5 | 1 | 1 | $2.363\\times10^{-5}$ / $2.367\\times10^{-5}$ | $1.432\\times10^{-14}$ / $9.680\\times10^{-15}$ |\n| 1000 | 0 | 1 | $6.510\\times10^{-10}$ / $6.984\\times10^{-10}$ | $2.421\\times10^{-14}$ / $3.261\\times10^{-14}$ |\n| 1000 | 1 | 0 | $1.403\\times10^{-12}$ / $1.022\\times10^{-11}$ | $8.888\\times10^{-15}$ / $8.469\\times10^{-15}$ |\n\n: Rest force $\\max\\lvert\\rho v_1\\rvert/(\\Delta t\\,g\\rho)$ after one RK3 step, five of the eight cases the test prints.\nEvidence: sha `e894700ff7aee30b52882e5202b16461413780b0`; deck `tests/test_x1_centroid_rest.py`; run `python\ntests/test_x1_centroid_rest.py` against the pin's build, 2026-10-10, CPU, double, 1 rank. {#tbl-ch05-x1cent-rest}\n\n**Evidence.** @tbl-ch05-x1cent-rest: with the switch the rest force is at round-off in every case; without it the\n$r_0/H=5$ column feels $2.4\\times10^{-5}$. The seam arm prints a split-against-one-block gap of 0 in both modes, and\nthe 2-rank arm 0 against both two blocks and one block [same sha; decks the test files; run `ctest -V`, 2026-10-10,\nCPU, double, 1 and 2 ranks].\n**Coverage.** CPU; the CUDA twins were not run (**pending: a CUDA run at the pin**).\n\n### Limits\n\n::: {.callout-warning title=\"Limits\"}\nThe switch does nothing on cubed-sphere grids. Under it `balance_column` balances only a column declared\n`geometry='cartesian'`.\n:::\n\n1. **Ratios of means.** The Favre velocity, $T$ and $\\rho/p$ are still treated as means; the $O(h^2/R)$ remainder is\n   @sec-ch05-oneoverr.\n2. **Cubed sphere.** Not implemented: the gnomonic grids store the mid-radius as $x_{1v}$ and would need the\n   conversion with their own radial measure.\n3. **Note history.** The copy of the derivation in `sources/deriv__x1-centroid-spherical.md` predates the seam\n   exchange and says the switch leaves the reference unchanged; at the pin it implies `SNAP_WB_REF4` and seam ghosts\n   are exchanged.\n4. **Untested combinations.** See the switch coverage matrix of Chapter 12.\n\n\n## The $1/R$ remainder on spherical-polar grids: what is left after the corrections (no switch) {#sec-ch05-oneoverr}\n\n<!-- PROVENANCE\npin: snapy@e894700ff7aee30b52882e5202b16461413780b0 (chengcli/snapy)\nsources: OUTLINE.md 5.9; docs/derivations/x1-centroid-spherical.md@e894700ff7aee30b52882e5202b16461413780b0 §6;\n         sources/study__next-1overR_README.md §§0-3; sources/gw__ONEOVERR_split_RESULT.md §§1-2;\n         sources/study__next-1overR-remainder_README.md §§0-4; ISSUES.md item 5\nstatus: draft\n-->\n\n### Summary\n\n::: {.callout-note title=\"At a glance\"}\n**What it is.** The part of the $1/R$ error of a spherical column that survives `SNAP_FLUX_COVARIANCE` and\n`SNAP_X1_CENTROID_EXACT`: an $O(h^2/R)$ term from reconstructing the Favre velocity\n$\\langle\\rho w\\rangle/\\langle\\rho\\rangle$ as if it were a plain mean.\n**Switch.** None; a property of the scheme. The related switches are `SNAP_FLUX_COVARIANCE` (Chapter 4),\n`SNAP_X1_CENTROID_EXACT` (@sec-ch05-x1cent) and `SNAP_GRAVITY_WORK_RADIAL_EXACT` (Chapter 6).\n**Order.** $O(h^2/R)$.\n**Defining equation.** @eq-ch05-oneoverr-favre.\n:::\n\nOn a spherical-polar grid the $r^2$ cell measure adds terms of relative size $h/R$ to every cell-to-face map, and the\ndivergence adds a $2/r$ factor to every flux error. Chapter 4's covariance corrections and the plain-mean maps of\n@sec-ch05-x1cent remove the leading such terms of the face fluxes, the reference and the pressure force. What remains\nis not a defect of any map but of an input: the $x_1$ velocity the maps reconstruct is a ratio of two $r^2$ means, not a\nmean, and the conversion of @eq-ch05-x1cent-conv makes means plain, not ratios exact. This section records that\nremainder, its signature, and what evidence exists for it at the pin; it has no code of its own.\n\n*Aliases.* \"the 1/R term\", \"leg (d)\" of #289; \"hypothesis H1\" in `sources/gw__ONEOVERR_split_RESULT.md`.\n\n### Derivation\n\nNotation as in @sec-ch05-x1cent; $R$ [m] is the radius of the column, $w=v_1$. The stored velocity of cell $i$ is the\nFavre mean $\\tilde w_i=\\langle\\rho w\\rangle_i/\\langle\\rho\\rangle_i$. Expanding $\\rho$ and $w$ about the mid-radius with the\nmoments of @eq-ch05-x1cent-defect, and the plain mean likewise,\n\n$$\n\\tilde w_i - \\overline w_i = \\frac{h_i^2}{12}\\,\\frac{\\rho'\\,w'}{\\rho} + \\delta_i\\,w' + O(h^4) ,\n$$ {#eq-ch05-oneoverr-favre}\n\nwhere the first term is the Cartesian covariance of a density-weighted mean and the second the centroid offset of the\n$r^2$ measure (this paragraph only: primes are $r$-derivatives; derived for linear $\\rho$ and $w$ in `[C21]`, exact in\nsympy). The conversion of @eq-ch05-x1cent-conv treats $\\tilde w$ as an $r^2$ mean and so removes the $\\delta_iw'$ part;\nthe covariance part stays. Reconstructing the converted value with weights for plain means therefore leaves an $O(h^2)$\nface error, which the $2/r$ of the radial divergence turns into an $O(h^2/R)$ tendency. The\nsame holds for $T=p/\\rho$ and for $\\rho/p$ inside the reference filter. The expansion follows\n`docs/derivations/x1-centroid-spherical.md@e894700ff7aee30b52882e5202b16461413780b0` §6; the harness and the\n$+g/(6c_pR)$ signature of the remainder in the effective stratification are in `sources/study__next-1overR_README.md`\n§§0-3, and the completeness of the face fluxes to $O(h^4)$ including $h^2/R$ is\n`sources/gw__ONEOVERR_split_RESULT.md` §§1-2.\n\n*Exact and truncated.* The remainder is $O(h^2/R)$ and vanishes for $R\\to\\infty$ (Cartesian).\n\n### Numerical method\n\n@fig-ch05-oneoverr-favre shows the effect in one cell. The terms involved live in the $x_1$ block of `HydroImpl::forward`\n(the plain-mean view of @sec-ch05-x1cent), in the covariance corrections of Chapter 4 and in the geometric sources of\n`SphericalPolarImpl::forward`; none of them is specific to this section.\n\n::: {#cell-fig-ch05-oneoverr-favre .cell execution_count=12}\n\n::: {.cell-output .cell-output-display execution_count=12}\n![Why a ratio of means is not a mean, in one radial cell. Black: a velocity profile w(r) across the cell; dashed blue: its plain mean; dotted vermillion: the Favre mean <rho w>/<rho> with density falling outward and the r^2 weight. The two means differ by O(h^2), which the x1 maps treat as if it were zero. Illustrative profiles.](05-well-balanced_files/figure-html/fig-ch05-oneoverr-favre-output-1.svg){#fig-ch05-oneoverr-favre fig-alt='A rising curve across the cell with two horizontal lines at slightly different heights, a dashed one and a dotted one.'}\n:::\n:::\n\n\nThe measured remainder needs a closure run in snapy at the pin (ISSUES.md item 5): $R[\\varepsilon n_1^2(R)-\\varepsilon\nn_1^2(\\infty)]$ against $R/H$ for the off and on arms, from a committed deck.\n\n::: {#cell-fig-ch05-oneoverr-remainder .cell execution_count=13}\n\n::: {.cell-output .cell-output-display execution_count=13}\n![The 1/R content of the one-step effective stratification, R times the difference from the Cartesian limit, against R/H, with SNAP_X1_CENTROID_EXACT off and on. Pending: needs the in-snapy closure run at the pin.](05-well-balanced_files/figure-html/fig-ch05-oneoverr-remainder-output-1.svg){#fig-ch05-oneoverr-remainder fig-alt='Placeholder for a plot of the 1/R content against R/H for two switch settings.'}\n:::\n:::\n\n\n### Code\n\nNo dedicated code. The pieces it depends on are listed in their own sections.\n\n| what | code link | symbol | switch |\n|--------|----------|----------|------|\n| the plain-mean view the maps read | [`hydro_forward.cpp:270-285`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L270-L285) | `x1_plain_means` | `SNAP_X1_CENTROID_EXACT` |\n| the radial source | [`spherical_polar.cpp:243-279`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/coord/spherical_polar.cpp#L243-L279) | `src1` | |\n\n: Code map of the $1/R$ remainder. {#tbl-ch05-oneoverr-code}\n\n### Tests\n\n| test (ctest name) | what it asserts | tolerance | where the tolerance comes from |\n|----------------|-------------|-----|-----|\n| none in ctest | no test asserts the remainder; `test_x1_centroid_rest_python` covers rest only | — | — |\n| this chapter's check, `[C21]` | the Favre-ratio expansion @eq-ch05-oneoverr-favre for linear profiles | exact | sympy |\n\n: Tests of the $1/R$ remainder. {#tbl-ch05-oneoverr-tests}\n\n**Evidence.** The derivation note quotes code values of the $1/R$ content, off and on, at $R/H$ = 5 to 1000 and $n_1$ =\n64 and 128, with no committed script or deck: **missing evidence**, and per ISSUES.md item 5 the one-step harness\nnumbers from commits not in snapy are not used. **Pending: an in-snapy closure run at the pin, with a committed deck,\nto rebuild the table and @fig-ch05-oneoverr-remainder.**\n**Coverage.** None.\n\n### Limits\n\n1. **Not removed.** The remainder is a known $O(h^2/R)$ term of the scheme; removing it would need the ratios\n   themselves made exact, which no switch does.\n2. **Metric of the harness.** The note reports column means with unit weight per cell; weighted by cell volume the\n   metric carries its own $1/R$ across the column's error profile and does not measure the scheme's term (same note,\n   §6).\n3. **Gravity-work interplay.** The face-form gravity work and its curvature flux on radial grids contribute their own\n   $1/R$ content; that is Chapter 6 (`sources/study__next-1overR-remainder_README.md` §§0-4).\n4. **Stale references.** The study READMEs were written before chengcli/snapy#293 merged; their file and line references\n   do not match the pin.\n\n\n## Legacy $x_1$ wall routines: isentropic wall ghosts and the wall-face state copy (no switch) {#sec-ch05-legacy}\n\n<!-- PROVENANCE\npin: snapy@e894700ff7aee30b52882e5202b16461413780b0 (chengcli/snapy)\nsources: OUTLINE.md 5.10; src/hydro/hydro.cpp; src/hydro/hydro_forward.cpp (described from the code)\nstatus: draft\n-->\n\n### Summary\n\n::: {.callout-note title=\"At a glance\"}\n**What it does.** Two older wall treatments of the non-well-balanced $x_1$ path: an isentropic extrapolation of $p$ and\n$\\rho$ into the wall ghosts (defined, never called) and a copy of the right state's $p$ and $\\rho$ into the left state\nat the wall face (called only on the non-well-balanced path with gravity on).\n**Switch.** None.\n**Status.** Effectively unreachable: with gravity on and any EOS other than `shallow-water` the well-balanced path of\n@sec-ch05-wbx1 runs instead, and the shallow-water EOS has no pressure row for these routines to use.\n**Defining equation.** @eq-ch05-legacy-copy.\n:::\n\nBefore the well-balanced reconstruction, a stratified column at a wall was handled by filling the ghost cells with an\nisentropic continuation of the wall cell and by making the two states at the wall face agree. Both routines are still\nin the code. The ghost fill's call in `HydroImpl::forward` is commented out; the face copy runs only on the $x_1$ path\ntaken when `wb_x1` is false and gravity is on, a combination no configuration reaches with a pressure row.\n\n### Derivation\n\nThe face copy sets, at the lower wall face $i_s-\\tfrac12$ (and symmetrically at the upper one),\n\n$$\n\\begin{aligned}\np^{L}_{i_s-1/2} &\\leftarrow p^{R}_{i_s-1/2}, \\\\\n\\rho^{L}_{i_s-1/2} &\\leftarrow \\rho^{R}_{i_s-1/2},\n\\end{aligned}\n$$ {#eq-ch05-legacy-copy}\n\nin `_revise_x1inner_lr`\n([`hydro.cpp:448-453`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L448-L453)),\nso the Riemann solver sees no pressure jump at the wall. The ghost fill holds $K=p/\\rho^\\gamma$ of the wall cell and\nintegrates $\\mathrm{d}(p^{a})/\\mathrm{d}x_1=-a\\,g/K^{1/\\gamma}$, $a=(\\gamma-1)/\\gamma$, cell by cell into the ghosts, the\nisentropic hydrostatic profile, in `_revise_x1inner_ghost`\n([`hydro.cpp:462-480`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L462-L480)).\nNeither is used at the pin, so neither has a check.\n\n### Numerical method\n\n@fig-ch05-legacy-lr shows the copy. It would run after the $x_1$ reconstruction, in every stage, on the faces of\nphysical $x_1$ walls.\n\n::: {#cell-fig-ch05-legacy-lr .cell execution_count=14}\n\n::: {.cell-output .cell-output-display execution_count=14}\n![The legacy wall-face copy at a bottom wall (thick black line), x1 to the right: the left state's p and rho at the wall face (orange triangle on the ghost side) are overwritten by the right state's (bluish-green arrow). The vermillion line under the hatched ghost cells marks the isentropic ghost fill, whose call is commented out.](05-well-balanced_files/figure-html/fig-ch05-legacy-lr-output-1.svg){#fig-ch05-legacy-lr fig-alt='Two hatched ghost cells and three interior cells meeting at a wall; two triangles at the wall face with an arrow from the right one to the left one; a line under the ghost cells.'}\n:::\n:::\n\n\n### Code\n\n| what | code link | symbol | switch |\n|--------|----------|----------|------|\n| face copy, lower and upper | [`hydro.cpp:448-460`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L448-L460) | `_revise_x1outer_lr` | |\n| isentropic ghosts, lower and upper | [`hydro.cpp:462-500`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro.cpp#L462-L500) | `_revise_x1outer_ghost` | |\n| the commented-out call | [`hydro_forward.cpp:247-250`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L247-L250) | `_revise_x1inner_ghost` | |\n| the only live call | [`hydro_forward.cpp:378-384`](https://github.com/chengcli/snapy/blob/e894700ff7aee30b52882e5202b16461413780b0/src/hydro/hydro_forward.cpp#L378-L384) | `_revise_x1inner_lr` | `wb_x1` false, gravity on |\n\n: Code map of the legacy wall routines. {#tbl-ch05-legacy-code}\n\n### Tests\n\nNo test exercises either routine at the pin; the live call is unreachable in every registered test.\n\n### Limits\n\n1. **Dead code.** The ghost fill is never called and the face copy is unreachable with a pressure row; they are kept,\n   not maintained.\n2. **If revived.** The isentropic fill assumes one $\\gamma$ for the column and an isentropic wall region; it would\n   conflict with the even-parity perturbation ghosts of @sec-ch05-wbx1.\n\n",
    "supporting": [
      "05-well-balanced_files"
    ],
    "filters": [],
    "includes": {}
  }
}